In [1]:
# ** This cell is needed since we are not in the src directory 
import sys 
import os
# Add the src/ directory to the Python path
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "../src/")))

ROOT_DIR = ".."
SRC_DIR = ROOT_DIR + "/src"

import sys
sys.path.append("/Users/admin/eeg-ds004504/")

In [2]:
from config_handler import initiate_config, load_config

initiate_config()

{'data_path': '/Users/admin/eeg-ds004504',
 'derivatives': True,
 'freqBands': {'Alpha': [8, 12],
  'Beta': [12, 30],
  'Delta': [0.5, 4],
  'Theta': [4, 8],
  'custom1': [9, 11]},
 'method': 'welch',
 'stepSize': 0.3,
 'windowLength': 3}

In [3]:
print(load_config())

{'data_path': '/Users/admin/eeg-ds004504', 'derivatives': True, 'freqBands': {'Alpha': [8, 12], 'Beta': [12, 30], 'Delta': [0.5, 4], 'Theta': [4, 8], 'custom1': [9, 11]}, 'method': 'welch', 'stepSize': 0.3, 'windowLength': 3}

In [4]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import pandas_udf, PandasUDFType
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, DoubleType, ArrayType, MapType
import pandas as pd

In [5]:
# Check if there's an active Spark context and stop it
from pyspark import SparkContext
if SparkContext._active_spark_context:
    print("Stopping existing Spark context...")
    SparkContext._active_spark_context.stop()
    print("Previous Spark context stopped successfully")

In [6]:
# creating the ultimate most optimised spark session ever muwahaha
import os
from pyspark.sql import SparkSession

# Set Java options for the JVM running Spark
# -Xmx12g : Sets the maximum heap size to 12GB
# -Xms4g : Sets the initial heap size to 4GB to avoid resizing overhead
os.environ["_JAVA_OPTIONS"] = "-Xmx16g -Xms8g"

# Build Spark session with memory, parallelism, and network settings
spark = (
    SparkSession.builder 
    # Application name shown in Spark UI
    .appName("EEG_Analysis") 

    # SPARK DIRECTORY FOR THREADS / PERSIST
    
    # Use all available logical cores or specify a number
    # "local[*]" uses all available cores, "local[12]" limits to 12 threads
    .config("spark.master", "local[12]") \

    # Executor memory: how much memory each Spark worker can use
    .config("spark.executor.memory", "8g") \

    # Driver memory: memory available to the Spark driver (main Python process)
    .config("spark.driver.memory", "8g") \
    
    # THIS IS WHERE SPARK WILL PUT ITS TEMPERARY VARIABLES 
    # .config("spark.local.dir", os.path.expanduser("~/external-spark-tmp"))

    # Number of shuffle partitions (e.g., after groupBy, join, etc.)
    # Lower this in local mode to reduce overhead (default is 200)
    .config("spark.sql.shuffle.partitions", "12") \

    # Default number of partitions in operations like parallelize
    .config("spark.default.parallelism", "12") \

    # Maximum size (in MB) allowed for any RPC message (e.g., large UDF closures or data broadcasts)
    .config("spark.rpc.message.maxSize", "512") \

    # prevent breaking pipes 
    .config("spark.reducer.maxReqsInFlight", "1") \
    .config("spark.shuffle.io.preferDirectBufs", "false") \
    .config("spark.shuffle.file.buffer", "32k") \
    
    # Required for avoiding binding issues on some MacOS environments
    .config("spark.driver.bindAddress", "127.0.0.1") \
    .config("spark.driver.host", "127.0.0.1") 
    .getOrCreate()
)

    # ----------------------------------------
    # Additional advanced options (optional):
    # ----------------------------------------

    # Use Kryo serializer instead of default Java serializer for better performance
    # .config("spark.serializer", "org.apache.spark.serializer.KryoSerializer") \

    # Increase broadcast join timeout (in seconds) for large models or lookup tables
    # .config("spark.sql.broadcastTimeout", "600") \

    # Fraction of JVM memory reserved for execution and storage (default is 0.6)
    # .config("spark.memory.fraction", "0.8") \

    # Portion of memory reserved for caching/storage (default is 0.5 of memory.fraction)
    # .config("spark.memory.storageFraction", "0.3") \

    # Enable Apache Arrow for efficient pandas-to-Spark conversion (useful with UDFs)
    # .config("spark.sql.execution.arrow.pyspark.enabled", "true") \

    # Finalize and create the Spark session


# spark = SparkSession.builder.appName("MyApp").getOrCreate()

print("New Spark session created successfully")

Picked up _JAVA_OPTIONS: -Xmx16g -Xms8g
Picked up _JAVA_OPTIONS: -Xmx16g -Xms8g
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
25/04/22 03:36:59 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

New Spark session created successfully

In [7]:
for item in spark.sparkContext.getConf().getAll():
    print(item)

('spark.driver.extraJavaOptions', '-Djava.net.preferIPv6Addresses=false -XX:+IgnoreUnrecognizedVMOptions --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.nio.cs=ALL-UNNAMED --add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED --add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED -Djdk.reflect.useDirectMethodHandle=false')
('spark.app.startTime', '1745307419810')
('spark.default.parallelism', '12')
('spark.driver.host', '127.0.0.1')
('spark.app.id', 'local-1745307420271')
('spark.executor.id', 'driver')
('spark.shuffle.file.buffer', '32k')
('spark.reducer.maxReqsInFlight', '1')
('spark.sql.shuffle.partitions', '12')
('spark.driver.bindAddress', '127.0.0.1')
('spark.shuffle.io.preferDirectBufs', 'false')
('spark.app.submitTime', '1745307419711')
('spark.master', 'local[12]')
('spark.rpc.message.maxSize', '512')
('spark.rdd.compress', 'True')
('spark.app.name', 'EEG_Analysis')
('spark.executor.extraJavaOptions', '-Djava.net.preferIPv6Addresses=false -XX:+IgnoreUnrecognizedVMOptions --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.nio.cs=ALL-UNNAMED --add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED --add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED -Djdk.reflect.useDirectMethodHandle=false')
('spark.driver.memory', '8g')
('spark.serializer.objectStreamReset', '100')
('spark.submit.pyFiles', '')
('spark.executor.memory', '8g')
('spark.submit.deployMode', 'client')
('spark.ui.showConsoleProgress', 'true')
('spark.driver.port', '49680')

In [8]:
def reload_my_modules():
    import importlib
    import populate_schemas
    import feature_extraction
    import schema_definition
    importlib.reload(populate_schemas)
    importlib.reload(feature_extraction)
    importlib.reload(schema_definition)

reload_my_modules()


from populate_schemas import load_subjects_df, extract_features_udtf
from feature_extraction import processEpoch, processSub
from schema_definition import get_feature_schema, get_subject_schema

sc = spark.sparkContext # we pass udf/udtf's (user defind functions and user defined table functions) to spark so it can access them

# Making all necessary modules available to spark
try: 
    # oh btw spark is werid about not finding the config but it always finds it somehow not sure how that works not going to look rn tbh
    # ^ so feature_extraction has extra print statements
    sc.addPyFile(os.path.join(SRC_DIR, "feature_extraction.py"))
    print("Added feature_extraction.py to the pyspark context")
    sc.addPyFile(os.path.join(SRC_DIR, "preprocess_sets.py"))
    print("Added preprocess_sets to the pyspark context")
    sc.addPyFile(os.path.join(SRC_DIR, "schema_definition.py"))
    print("Added schema_definition.py to the pyspark context")
    sc.addPyFile(os.path.join(SRC_DIR, "config_handler.py"))
    print("Added config_handler.py to the pyspark context")
except Exception as e:
    print(f"Error adding files to SparkContext: {e}")

Config not found in feature_extraction.py
Config using in feature Extraction.py {'data_path': '/Users/admin/eeg-ds004504', 'derivatives': True, 'freqBands': {'Alpha': [8, 12], 'Beta': [12, 30], 'Delta': [0.5, 4], 'Theta': [4, 8], 'custom1': [9, 11]}, 'method': 'welch', 'stepSize': 0.3, 'windowLength': 3}
Config using in feature Extraction.py {'data_path': '/Users/admin/eeg-ds004504', 'derivatives': True, 'freqBands': {'Alpha': [8, 12], 'Beta': [12, 30], 'Delta': [0.5, 4], 'Theta': [4, 8], 'custom1': [9, 11]}, 'method': 'welch', 'stepSize': 0.3, 'windowLength': 3}
Config using in feature Extraction.py {'data_path': '/Users/admin/eeg-ds004504', 'derivatives': True, 'freqBands': {'Alpha': [8, 12], 'Beta': [12, 30], 'Delta': [0.5, 4], 'Theta': [4, 8], 'custom1': [9, 11]}, 'method': 'welch', 'stepSize': 0.3, 'windowLength': 3}
Added feature_extraction.py to the pyspark context
Added preprocess_sets to the pyspark context
Added schema_definition.py to the pyspark context
Added config_handler.py to the pyspark context

In [9]:
import pandas as pd

# alz_df_pandas = pd.read_pickle("alz_df_apr10_1355.pkl")
# cntrl_df_pandas = pd.read_pickle("cntrl_df_apr10_1355.pkl")


# alz_df_pandas = pd.read_pickle("features_alz_extra_features_Apr15_1033.pkl")
# cntrl_df_pandas = pd.read_pickle("features_cntrl_extra_features_Apr15_1033.pkl")

alz_df_pandas = pd.read_pickle("features_alz_extra_features_Apr19_2141.pkl")
cntrl_df_pandas = pd.read_pickle("features_cntrl_extra_features_Apr19_2141.pkl")

In [10]:
%%time
alz_df_spark = spark.createDataFrame(alz_df_pandas)
cntrl_df_spark = spark.createDataFrame(cntrl_df_pandas)

KeyboardInterrupt:

In [14]:
%%time
alz_df_spark = spark.read.parquet("features_alz_extra_features_Apr19_2141.parquet")
cntrl_df_spark = spark.read.parquet("features_cntrl_extra_features_Apr19_2141.parquet")

CPU times: user 2.23 ms, sys: 3.32 ms, total: 5.55 ms
Wall time: 664 ms

In [15]:
# alz_df_spark.parquet("spark_features_alz_extra_features_Apr19_2141.parquet")
# cntrl_df_spark.parquet("spark_features_cntrl_extra_features_Apr19_2141.parquet")

In [16]:
#just renaming things now that we understand the types and where things are coming from
alz_df = alz_df_spark
cntrl_df = cntrl_df_spark

In [17]:
alz_df.show()

+---------+-------+---------+--------+-----------+-------------+----------+
|SubjectID|EpochID|Electrode|WaveBand|FeatureName| FeatureValue|table_type|
+---------+-------+---------+--------+-----------+-------------+----------+
|  sub-008|   ep-0|      Fp1|   Alpha|      Power|  7.020328E-4|      band|
|  sub-008|   ep-0|      Fp1|    Beta|      Power|  3.399499E-4|      band|
|  sub-008|   ep-0|      Fp1|   Delta|      Power|  0.087231696|      band|
|  sub-008|   ep-0|      Fp1|   Theta|      Power| 0.0011391409|      band|
|  sub-008|   ep-0|      Fp1| custom1|      Power| 4.2795436E-4|      band|
|  sub-008|   ep-0|      Fp1|    NULL|TotalEnergy|   0.34805238| electrode|
|  sub-008|   ep-0|      Fp1|    NULL| TotalPower|  0.011235955| electrode|
|  sub-008|   ep-0|      Fp2|   Alpha|      Power| 0.0014689578|      band|
|  sub-008|   ep-0|      Fp2|    Beta|      Power|  5.043481E-4|      band|
|  sub-008|   ep-0|      Fp2|   Delta|      Power|   0.08462298|      band|
|  sub-008|   ep-0|      Fp2|   Theta|      Power|  0.002023743|      band|
|  sub-008|   ep-0|      Fp2| custom1|      Power| 0.0011395817|      band|
|  sub-008|   ep-0|      Fp2|    NULL|TotalEnergy|   0.26473707| electrode|
|  sub-008|   ep-0|      Fp2|    NULL| TotalPower|  0.011235955| electrode|
|  sub-008|   ep-0|       F3|   Alpha|      Power| 3.3144082E-4|      band|
|  sub-008|   ep-0|       F3|    Beta|      Power|1.05723055E-4|      band|
|  sub-008|   ep-0|       F3|   Delta|      Power|   0.08852561|      band|
|  sub-008|   ep-0|       F3|   Theta|      Power|  0.001377665|      band|
|  sub-008|   ep-0|       F3| custom1|      Power| 2.9761362E-4|      band|
|  sub-008|   ep-0|       F3|    NULL|TotalEnergy|   0.41476318| electrode|
+---------+-------+---------+--------+-----------+-------------+----------+
only showing top 20 rows

# Raw Data Visualization

# Start of data processing

In [18]:
# give each its respective labels
from pyspark.sql.functions import lit
alz_df = alz_df.withColumn("label", lit(1)).repartition(8).persist()
cntrl_df = cntrl_df.withColumn("label", lit(0)).repartition(8).persist()

In [19]:
# union everything
full_df = alz_df.unionByName(cntrl_df)

In [20]:
# Split based on feature type
from pyspark.sql.functions import col

band_df = full_df.filter(col("table_type") == "band")
channel_df = full_df.filter(col("table_type") == "electrode")
epoch_df = full_df.filter(col("table_type") == "epoch")

In [21]:
alz_df.unpersist()
cntrl_df.unpersist()

DataFrame[SubjectID: string, EpochID: string, Electrode: string, WaveBand: string, FeatureName: string, FeatureValue: float, table_type: string, label: int]

In [23]:
from pyspark.sql.functions import col

# Filter and save each to Parquet
full_df.filter(col("table_type") == "band") \
    .write.mode("overwrite").parquet("tempParquets/band_df")

full_df.filter(col("table_type") == "electrode") \
    .write.mode("overwrite").parquet("tempParquets/channel_df")

full_df.filter(col("table_type") == "epoch") \
    .write.mode("overwrite").parquet("tempParquets/epoch_df")

In [24]:
import os
os.system('say "START!"')

0

In [25]:
from pyspark.sql.functions import first
from pyspark.sql.functions import concat_ws


# Band-level: Electrode_WaveBand_Feature
band_df = band_df.withColumn("pivot", concat_ws("_", "Electrode", "WaveBand", "FeatureName")).repartition(1000, "SubjectID").persist()

# band_df.write.mode("overwrite").parquet("band_pre_pivot")
# Pivot band-level features
band_pivot = band_df.groupBy("SubjectID", "EpochID", "label").pivot("pivot").agg(first("FeatureValue"))
band_df.unpersist()

# Channel-level: Electrode_Feature
channel_df = channel_df.withColumn("pivot", concat_ws("_", "Electrode", "FeatureName")).repartition(1000, "SubjectID").persist()
# channel_df.write.mode("overwrite").parquet("channel_df_pre_pivot")

# Pivot channel-level features
channel_pivot = channel_df.groupBy("SubjectID", "EpochID", "label").pivot("pivot").agg(first("FeatureValue"))
channel_pivot.unpersist()


# Band-level: Electrode_WaveBand_Feature
epoch_df = epoch_df.withColumn("pivot", col("FeatureName")).repartition(1000, "SubjectID").persist()
# epoch_df.write.mode("overwrite").parquet("epoch_df_pre_pivot")


# Pivot epoch-level features
epoch_pivot = epoch_df.groupBy("SubjectID", "EpochID", "label").pivot("pivot").agg(first("FeatureValue"))
epoch_pivot.unpersist()

DataFrame[SubjectID: string, EpochID: string, label: int, AppEntropy: float, HiguchiFD: float, HjorthComplexity: float, HjorthMobility: float, KatzFD: float, Kurtosis: float, Mean: float, RMS: float, SampleEntropy: float, Skewness: float, Std: float, Variance: float]

In [26]:
import os
os.system('say "DONE!"')

0

In [27]:
from pyspark.sql.functions import first

# Pivot band-level features
band_pivot = band_df.groupBy("SubjectID", "EpochID", "label").pivot("pivot").agg(first("FeatureValue"))

# Pivot channel-level features
channel_pivot = channel_df.groupBy("SubjectID", "EpochID", "label").pivot("pivot").agg(first("FeatureValue"))

# Pivot epoch-level features
epoch_pivot = epoch_df.groupBy("SubjectID", "EpochID", "label").pivot("pivot").agg(first("FeatureValue"))

In [28]:
from functools import reduce

# full_df = reduce(
#     lambda df1, df2: df1.join(df2, on=["SubjectID", "EpochID", "label"], how="outer"),
#     [band_pivot, channel_pivot, epoch_pivot]
# ).fillna(0.0)


full_df = reduce(
    lambda df1, df2: df1.join(df2, on=["SubjectID", "EpochID", "label"], how="outer"),
     [band_pivot, channel_pivot, epoch_pivot]# band_pivot, channel_pivot, epoch_pivot]
).fillna(0.0)
full_df.repartition(16).persist()

25/04/22 03:45:04 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

DataFrame[SubjectID: string, EpochID: string, label: int, C3_Alpha_Power: float, C3_Beta_Power: float, C3_Delta_Power: float, C3_Theta_Power: float, C3_custom1_Power: float, C4_Alpha_Power: float, C4_Beta_Power: float, C4_Delta_Power: float, C4_Theta_Power: float, C4_custom1_Power: float, Cz_Alpha_Power: float, Cz_Beta_Power: float, Cz_Delta_Power: float, Cz_Theta_Power: float, Cz_custom1_Power: float, F3_Alpha_Power: float, F3_Beta_Power: float, F3_Delta_Power: float, F3_Theta_Power: float, F3_custom1_Power: float, F4_Alpha_Power: float, F4_Beta_Power: float, F4_Delta_Power: float, F4_Theta_Power: float, F4_custom1_Power: float, F7_Alpha_Power: float, F7_Beta_Power: float, F7_Delta_Power: float, F7_Theta_Power: float, F7_custom1_Power: float, F8_Alpha_Power: float, F8_Beta_Power: float, F8_Delta_Power: float, F8_Theta_Power: float, F8_custom1_Power: float, Fp1_Alpha_Power: float, Fp1_Beta_Power: float, Fp1_Delta_Power: float, Fp1_Theta_Power: float, Fp1_custom1_Power: float, Fp2_Alpha_Power: float, Fp2_Beta_Power: float, Fp2_Delta_Power: float, Fp2_Theta_Power: float, Fp2_custom1_Power: float, Fz_Alpha_Power: float, Fz_Beta_Power: float, Fz_Delta_Power: float, Fz_Theta_Power: float, Fz_custom1_Power: float, O1_Alpha_Power: float, O1_Beta_Power: float, O1_Delta_Power: float, O1_Theta_Power: float, O1_custom1_Power: float, O2_Alpha_Power: float, O2_Beta_Power: float, O2_Delta_Power: float, O2_Theta_Power: float, O2_custom1_Power: float, P3_Alpha_Power: float, P3_Beta_Power: float, P3_Delta_Power: float, P3_Theta_Power: float, P3_custom1_Power: float, P4_Alpha_Power: float, P4_Beta_Power: float, P4_Delta_Power: float, P4_Theta_Power: float, P4_custom1_Power: float, Pz_Alpha_Power: float, Pz_Beta_Power: float, Pz_Delta_Power: float, Pz_Theta_Power: float, Pz_custom1_Power: float, T3_Alpha_Power: float, T3_Beta_Power: float, T3_Delta_Power: float, T3_Theta_Power: float, T3_custom1_Power: float, T4_Alpha_Power: float, T4_Beta_Power: float, T4_Delta_Power: float, T4_Theta_Power: float, T4_custom1_Power: float, T5_Alpha_Power: float, T5_Beta_Power: float, T5_Delta_Power: float, T5_Theta_Power: float, T5_custom1_Power: float, T6_Alpha_Power: float, T6_Beta_Power: float, T6_Delta_Power: float, T6_Theta_Power: float, T6_custom1_Power: float, C3_TotalEnergy: float, C3_TotalPower: float, C4_TotalEnergy: float, C4_TotalPower: float, Cz_TotalEnergy: float, Cz_TotalPower: float, F3_TotalEnergy: float, F3_TotalPower: float, F4_TotalEnergy: float, F4_TotalPower: float, F7_TotalEnergy: float, F7_TotalPower: float, F8_TotalEnergy: float, F8_TotalPower: float, Fp1_TotalEnergy: float, Fp1_TotalPower: float, Fp2_TotalEnergy: float, Fp2_TotalPower: float, Fz_TotalEnergy: float, Fz_TotalPower: float, O1_TotalEnergy: float, O1_TotalPower: float, O2_TotalEnergy: float, O2_TotalPower: float, P3_TotalEnergy: float, P3_TotalPower: float, P4_TotalEnergy: float, P4_TotalPower: float, Pz_TotalEnergy: float, Pz_TotalPower: float, T3_TotalEnergy: float, T3_TotalPower: float, T4_TotalEnergy: float, T4_TotalPower: float, T5_TotalEnergy: float, T5_TotalPower: float, T6_TotalEnergy: float, T6_TotalPower: float, AppEntropy: float, HiguchiFD: float, HjorthComplexity: float, HjorthMobility: float, KatzFD: float, Kurtosis: float, Mean: float, RMS: float, SampleEntropy: float, Skewness: float, Std: float, Variance: float]

In [29]:
band_pivot.unpersist()
channel_pivot.unpersist()
epoch_pivot.unpersist()

DataFrame[SubjectID: string, EpochID: string, label: int, AppEntropy: float, HiguchiFD: float, HjorthComplexity: float, HjorthMobility: float, KatzFD: float, Kurtosis: float, Mean: float, RMS: float, SampleEntropy: float, Skewness: float, Std: float, Variance: float]

In [30]:
type(full_df)

pyspark.sql.dataframe.DataFrame

In [31]:
full_df.repartition(16).persist()

25/04/22 03:45:07 WARN CacheManager: Asked to cache already cached data.

DataFrame[SubjectID: string, EpochID: string, label: int, C3_Alpha_Power: float, C3_Beta_Power: float, C3_Delta_Power: float, C3_Theta_Power: float, C3_custom1_Power: float, C4_Alpha_Power: float, C4_Beta_Power: float, C4_Delta_Power: float, C4_Theta_Power: float, C4_custom1_Power: float, Cz_Alpha_Power: float, Cz_Beta_Power: float, Cz_Delta_Power: float, Cz_Theta_Power: float, Cz_custom1_Power: float, F3_Alpha_Power: float, F3_Beta_Power: float, F3_Delta_Power: float, F3_Theta_Power: float, F3_custom1_Power: float, F4_Alpha_Power: float, F4_Beta_Power: float, F4_Delta_Power: float, F4_Theta_Power: float, F4_custom1_Power: float, F7_Alpha_Power: float, F7_Beta_Power: float, F7_Delta_Power: float, F7_Theta_Power: float, F7_custom1_Power: float, F8_Alpha_Power: float, F8_Beta_Power: float, F8_Delta_Power: float, F8_Theta_Power: float, F8_custom1_Power: float, Fp1_Alpha_Power: float, Fp1_Beta_Power: float, Fp1_Delta_Power: float, Fp1_Theta_Power: float, Fp1_custom1_Power: float, Fp2_Alpha_Power: float, Fp2_Beta_Power: float, Fp2_Delta_Power: float, Fp2_Theta_Power: float, Fp2_custom1_Power: float, Fz_Alpha_Power: float, Fz_Beta_Power: float, Fz_Delta_Power: float, Fz_Theta_Power: float, Fz_custom1_Power: float, O1_Alpha_Power: float, O1_Beta_Power: float, O1_Delta_Power: float, O1_Theta_Power: float, O1_custom1_Power: float, O2_Alpha_Power: float, O2_Beta_Power: float, O2_Delta_Power: float, O2_Theta_Power: float, O2_custom1_Power: float, P3_Alpha_Power: float, P3_Beta_Power: float, P3_Delta_Power: float, P3_Theta_Power: float, P3_custom1_Power: float, P4_Alpha_Power: float, P4_Beta_Power: float, P4_Delta_Power: float, P4_Theta_Power: float, P4_custom1_Power: float, Pz_Alpha_Power: float, Pz_Beta_Power: float, Pz_Delta_Power: float, Pz_Theta_Power: float, Pz_custom1_Power: float, T3_Alpha_Power: float, T3_Beta_Power: float, T3_Delta_Power: float, T3_Theta_Power: float, T3_custom1_Power: float, T4_Alpha_Power: float, T4_Beta_Power: float, T4_Delta_Power: float, T4_Theta_Power: float, T4_custom1_Power: float, T5_Alpha_Power: float, T5_Beta_Power: float, T5_Delta_Power: float, T5_Theta_Power: float, T5_custom1_Power: float, T6_Alpha_Power: float, T6_Beta_Power: float, T6_Delta_Power: float, T6_Theta_Power: float, T6_custom1_Power: float, C3_TotalEnergy: float, C3_TotalPower: float, C4_TotalEnergy: float, C4_TotalPower: float, Cz_TotalEnergy: float, Cz_TotalPower: float, F3_TotalEnergy: float, F3_TotalPower: float, F4_TotalEnergy: float, F4_TotalPower: float, F7_TotalEnergy: float, F7_TotalPower: float, F8_TotalEnergy: float, F8_TotalPower: float, Fp1_TotalEnergy: float, Fp1_TotalPower: float, Fp2_TotalEnergy: float, Fp2_TotalPower: float, Fz_TotalEnergy: float, Fz_TotalPower: float, O1_TotalEnergy: float, O1_TotalPower: float, O2_TotalEnergy: float, O2_TotalPower: float, P3_TotalEnergy: float, P3_TotalPower: float, P4_TotalEnergy: float, P4_TotalPower: float, Pz_TotalEnergy: float, Pz_TotalPower: float, T3_TotalEnergy: float, T3_TotalPower: float, T4_TotalEnergy: float, T4_TotalPower: float, T5_TotalEnergy: float, T5_TotalPower: float, T6_TotalEnergy: float, T6_TotalPower: float, AppEntropy: float, HiguchiFD: float, HjorthComplexity: float, HjorthMobility: float, KatzFD: float, Kurtosis: float, Mean: float, RMS: float, SampleEntropy: float, Skewness: float, Std: float, Variance: float]

In [ ]:
full_df.write.mode("overwrite").parquet("tempParquets/full_df")

[Stage 191:==============>                                    (290 + 13) / 1000]]

In [48]:
print("w")

w

In [ ]:
NUM_TEST_SUBJECTS_PER_GROUP = 2

# Get test subject IDs from full_df (which has .label)
alz_test_subjects = (
    full_df.filter("label == 1")
    .select("SubjectID")
    .distinct()
    .orderBy("SubjectID")
    .limit(NUM_TEST_SUBJECTS_PER_GROUP)
    .rdd.flatMap(lambda row: row)
    .collect()
)

cntrl_test_subjects = (
    full_df.filter("label == 0")
    .select("SubjectID")
    .distinct()
    .orderBy("SubjectID")
    .limit(NUM_TEST_SUBJECTS_PER_GROUP)
    .rdd.flatMap(lambda row: row)
    .collect()
)

test_subjects = alz_test_subjects + cntrl_test_subjects #this will be the firs 2 subjects of each group for reproduceablility

In [49]:
print("w")

w

In [ ]:
# from pyspark.sql.functions import rand

# NUM_TEST_SUBJECTS_PER_GROUP = 2
# SEED = 42

# # Alzheimer's test subjects (label == 1)
# alz_test_subjects = (
#     full_df.filter("label == 1")
#     .select("SubjectID")
#     .distinct()
#     .orderBy(rand(SEED))  # Randomize with seed
#     .limit(NUM_TEST_SUBJECTS_PER_GROUP)
#     .rdd.flatMap(lambda row: row)
#     .collect()
# )

# # Control test subjects (label == 0)
# cntrl_test_subjects = (
#     full_df.filter("label == 0")
#     .select("SubjectID")
#     .distinct()
#     .orderBy(rand(SEED + 1))  # Different seed for different shuffle
#     .limit(NUM_TEST_SUBJECTS_PER_GROUP)
#     .rdd.flatMap(lambda row: row)
#     .collect()
# )

# # Combine test subjects
# test_subjects = alz_test_subjects + cntrl_test_subjects

In [ ]:
print(f"alz_test_subjects {alz_test_subjects}")
print(f"cntrl_test_subjects {cntrl_test_subjects}")

In [ ]:
# Split into test and train sets
test_df = full_df.filter(col("SubjectID").isin(test_subjects))
train_df = full_df.filter(~col("SubjectID").isin(test_subjects))

In [ ]:
print("got here")

# DO T-TEST HERE !!

In [50]:
train_df.columns

['SubjectID',
 'EpochID',
 'label',
 'C3_Alpha_Power',
 'C3_Beta_Power',
 'C3_Delta_Power',
 'C3_Theta_Power',
 'C3_custom1_Power',
 'C4_Alpha_Power',
 'C4_Beta_Power',
 'C4_Delta_Power',
 'C4_Theta_Power',
 'C4_custom1_Power',
 'Cz_Alpha_Power',
 'Cz_Beta_Power',
 'Cz_Delta_Power',
 'Cz_Theta_Power',
 'Cz_custom1_Power',
 'F3_Alpha_Power',
 'F3_Beta_Power',
 'F3_Delta_Power',
 'F3_Theta_Power',
 'F3_custom1_Power',
 'F4_Alpha_Power',
 'F4_Beta_Power',
 'F4_Delta_Power',
 'F4_Theta_Power',
 'F4_custom1_Power',
 'F7_Alpha_Power',
 'F7_Beta_Power',
 'F7_Delta_Power',
 'F7_Theta_Power',
 'F7_custom1_Power',
 'F8_Alpha_Power',
 'F8_Beta_Power',
 'F8_Delta_Power',
 'F8_Theta_Power',
 'F8_custom1_Power',
 'Fp1_Alpha_Power',
 'Fp1_Beta_Power',
 'Fp1_Delta_Power',
 'Fp1_Theta_Power',
 'Fp1_custom1_Power',
 'Fp2_Alpha_Power',
 'Fp2_Beta_Power',
 'Fp2_Delta_Power',
 'Fp2_Theta_Power',
 'Fp2_custom1_Power',
 'Fz_Alpha_Power',
 'Fz_Beta_Power',
 'Fz_Delta_Power',
 'Fz_Theta_Power',
 'Fz_custom1_Power',
 'O1_Alpha_Power',
 'O1_Beta_Power',
 'O1_Delta_Power',
 'O1_Theta_Power',
 'O1_custom1_Power',
 'O2_Alpha_Power',
 'O2_Beta_Power',
 'O2_Delta_Power',
 'O2_Theta_Power',
 'O2_custom1_Power',
 'P3_Alpha_Power',
 'P3_Beta_Power',
 'P3_Delta_Power',
 'P3_Theta_Power',
 'P3_custom1_Power',
 'P4_Alpha_Power',
 'P4_Beta_Power',
 'P4_Delta_Power',
 'P4_Theta_Power',
 'P4_custom1_Power',
 'Pz_Alpha_Power',
 'Pz_Beta_Power',
 'Pz_Delta_Power',
 'Pz_Theta_Power',
 'Pz_custom1_Power',
 'T3_Alpha_Power',
 'T3_Beta_Power',
 'T3_Delta_Power',
 'T3_Theta_Power',
 'T3_custom1_Power',
 'T4_Alpha_Power',
 'T4_Beta_Power',
 'T4_Delta_Power',
 'T4_Theta_Power',
 'T4_custom1_Power',
 'T5_Alpha_Power',
 'T5_Beta_Power',
 'T5_Delta_Power',
 'T5_Theta_Power',
 'T5_custom1_Power',
 'T6_Alpha_Power',
 'T6_Beta_Power',
 'T6_Delta_Power',
 'T6_Theta_Power',
 'T6_custom1_Power',
 'C3_TotalEnergy',
 'C3_TotalPower',
 'C4_TotalEnergy',
 'C4_TotalPower',
 'Cz_TotalEnergy',
 'Cz_TotalPower',
 'F3_TotalEnergy',
 'F3_TotalPower',
 'F4_TotalEnergy',
 'F4_TotalPower',
 'F7_TotalEnergy',
 'F7_TotalPower',
 'F8_TotalEnergy',
 'F8_TotalPower',
 'Fp1_TotalEnergy',
 'Fp1_TotalPower',
 'Fp2_TotalEnergy',
 'Fp2_TotalPower',
 'Fz_TotalEnergy',
 'Fz_TotalPower',
 'O1_TotalEnergy',
 'O1_TotalPower',
 'O2_TotalEnergy',
 'O2_TotalPower',
 'P3_TotalEnergy',
 'P3_TotalPower',
 'P4_TotalEnergy',
 'P4_TotalPower',
 'Pz_TotalEnergy',
 'Pz_TotalPower',
 'T3_TotalEnergy',
 'T3_TotalPower',
 'T4_TotalEnergy',
 'T4_TotalPower',
 'T5_TotalEnergy',
 'T5_TotalPower',
 'T6_TotalEnergy',
 'T6_TotalPower',
 'AppEntropy',
 'HiguchiFD',
 'HjorthComplexity',
 'HjorthMobility',
 'KatzFD',
 'Kurtosis',
 'Mean',
 'RMS',
 'SampleEntropy',
 'Skewness',
 'Std',
 'Variance']

In [51]:
# import dimensionality_reduction
# import importlib
# importlib.reload(dimensionality_reduction)
# from dimensionality_reduction import min_max_normalize, normalize_by_column_per_subject_wide
# feature_cols = [c for c in train_df.columns if c not in ("SubjectID", "EpochID", "label")]


# # train_norm_df, test_norm_df = min_max_normalize(train_df, test_df, feature_cols)
# train_norm_df = normalize_by_column_per_subject_wide(train_df, feature_cols)
# test_norm_df = normalize_by_column_per_subject_wide(test_df, feature_cols)

In [52]:
train_df.head(1)

                                                                                ]

[Row(SubjectID='sub-003', EpochID='ep-1003', label=1, C3_Alpha_Power=0.0012282916577532887, C3_Beta_Power=0.00024898923584260046, C3_Delta_Power=0.08426367491483688, C3_Theta_Power=0.0037428848445415497, C3_custom1_Power=0.00141051912214607, C4_Alpha_Power=0.0023519701790064573, C4_Beta_Power=0.0002878349623642862, C4_Delta_Power=0.08370231091976166, C4_Theta_Power=0.002958987606689334, C4_custom1_Power=0.003850673558190465, Cz_Alpha_Power=0.0013206840958446264, Cz_Beta_Power=0.0001966899144463241, Cz_Delta_Power=0.08362051099538803, Cz_Theta_Power=0.004475411027669907, Cz_custom1_Power=0.001396479899995029, F3_Alpha_Power=0.0036768284626305103, F3_Beta_Power=0.00024767022114247084, F3_Delta_Power=0.07738445699214935, F3_Theta_Power=0.007606237195432186, F3_custom1_Power=0.002669800305739045, F4_Alpha_Power=0.0031283418647944927, F4_Beta_Power=0.00026330543914809823, F4_Delta_Power=0.07639987766742706, F4_Theta_Power=0.00898689404129982, F4_custom1_Power=0.003181564388796687, F7_Alpha_Power=0.0036267030518501997, F7_Beta_Power=0.00023229520593304187, F7_Delta_Power=0.07846151292324066, F7_Theta_Power=0.006738248281180859, F7_custom1_Power=0.003170226700603962, F8_Alpha_Power=0.003945797681808472, F8_Beta_Power=0.0002454555651638657, F8_Delta_Power=0.07536463439464569, F8_Theta_Power=0.009198736399412155, F8_custom1_Power=0.003525947919115424, Fp1_Alpha_Power=0.0046999757178127766, Fp1_Beta_Power=0.000211202452192083, Fp1_Delta_Power=0.07508637756109238, Fp1_Theta_Power=0.008853767067193985, Fp1_custom1_Power=0.0036567116621881723, Fp2_Alpha_Power=0.004695575684309006, Fp2_Beta_Power=0.00024148751981556416, Fp2_Delta_Power=0.07185616344213486, Fp2_Theta_Power=0.011682913638651371, Fp2_custom1_Power=0.004304577596485615, Fz_Alpha_Power=0.004853592719882727, Fz_Beta_Power=0.00020917499205097556, Fz_Delta_Power=0.07411568611860275, Fz_Theta_Power=0.00959907379001379, Fz_custom1_Power=0.0044015576131641865, O1_Alpha_Power=0.004081398714333773, O1_Beta_Power=0.00022442445333581418, O1_Delta_Power=0.07821504026651382, O1_Theta_Power=0.006544904317706823, O1_custom1_Power=0.0022800180595368147, O2_Alpha_Power=0.0071205561980605125, O2_Beta_Power=0.0003524409548845142, O2_Delta_Power=0.07454009354114532, O2_Theta_Power=0.006298372056335211, O2_custom1_Power=0.006548371631652117, P3_Alpha_Power=0.0020998953841626644, P3_Beta_Power=0.00017714311252348125, P3_Delta_Power=0.08196069300174713, P3_Theta_Power=0.005305658094584942, P3_custom1_Power=0.001705230912193656, P4_Alpha_Power=0.005959407892078161, P4_Beta_Power=0.000313035910949111, P4_Delta_Power=0.07959412038326263, P4_Theta_Power=0.003003989579156041, P4_custom1_Power=0.007404756266623735, Pz_Alpha_Power=0.005391542799770832, Pz_Beta_Power=0.00024571054382249713, Pz_Delta_Power=0.07623666524887085, Pz_Theta_Power=0.00695248506963253, Pz_custom1_Power=0.00712946429848671, T3_Alpha_Power=0.002399957273155451, T3_Beta_Power=0.00021918331913184375, T3_Delta_Power=0.08301566541194916, T3_Theta_Power=0.0038493552710860968, T3_custom1_Power=0.0032630639616400003, T4_Alpha_Power=0.0024342979304492474, T4_Beta_Power=0.000282956229057163, T4_Delta_Power=0.08077937364578247, T4_Theta_Power=0.005577969830483198, T4_custom1_Power=0.0020854389294981956, T5_Alpha_Power=0.0044421241618692875, T5_Beta_Power=0.00019440722826402634, T5_Delta_Power=0.07855793088674545, T5_Theta_Power=0.006004937458783388, T5_custom1_Power=0.00425528921186924, T6_Alpha_Power=0.006087218411266804, T6_Beta_Power=0.0003483178443275392, T6_Delta_Power=0.07784820348024368, T6_Theta_Power=0.004317831713706255, T6_custom1_Power=0.005482912063598633, C3_TotalEnergy=0.29429784417152405, C3_TotalPower=0.01123595517128706, C4_TotalEnergy=0.27040863037109375, C4_TotalPower=0.01123595517128706, Cz_TotalEnergy=0.2692272663116455, Cz_TotalPower=0.01123595517128706, F3_TotalEnergy=0.25680771470069885, F3_TotalPower=0.01123595517128706, F4_TotalEnergy=0.23392482101917267, F4_TotalPower=0.01123595517128706, F7_TotalEnergy=0.2660597264766693, F7_TotalPower=0.01123595517128706, F8_TotalEnergy=0.23814603686332703, F8_TotalPower=0.01123595517128706, Fp1_TotalEnergy=0.224872425198555, Fp1_TotalPower=0.01123595517128706, Fp2_TotalEnergy=0.21992020308971405, Fp2_TotalPower=0.01123595517128706, Fz_TotalEnergy=0.2322452813386917, Fz_TotalPower=0.01123595517128706, O1_TotalEnergy=0.1820482611656189, O1_TotalPower=0.01123595517128706, O2_TotalEnergy=0.1501738429069519, O2_TotalPower=0.01123595517128706, P3_TotalEnergy=0.25355055928230286, P3_TotalPower=0.01123595517128706, P4_TotalEnergy=0.199327290058136, P4_TotalPower=0.01123595517128706, Pz_TotalEnergy=0.198486328125, Pz_TotalPower=0.01123595517128706, T3_TotalEnergy=0.2522481381893158, T3_TotalPower=0.01123595517128706, T4_TotalEnergy=0.2541011869907379, T4_TotalPower=0.01123595517128706, T5_TotalEnergy=0.2027813345193863, T5_TotalPower=0.01123595517128706, T6_TotalEnergy=0.21257518231868744, T6_TotalPower=0.01123595517128706, AppEntropy=0.5824080109596252, HiguchiFD=1.8075101375579834, HjorthComplexity=8.38398551940918, HjorthMobility=0.16328994929790497, KatzFD=2.083568572998047, Kurtosis=2.047619104385376, Mean=4.3247952486378775e-20, RMS=5.017127114115283e-05, SampleEntropy=0.5489991903305054, Skewness=0.16518829762935638, Std=5.018799129175022e-05, Variance=2.5225639355141993e-09)]

# NORMALIZING SUJBECT WIDE FOR EXPERIMENT< REMOVE!, MIN MAX< TRY DIFFERNET COMBOS FOR LOWER COHEN!

In [83]:
import importlib
try:
    importlib.reload(dimensionality_reduction)
except:
    pass
from dimensionality_reduction import min_max_normalize, normalize_by_column, normalize_by_column_per_subject_wide

normalize_by_column_per_subject_wide(

In [53]:
# train_df.schema

In [54]:
# import dimensionality_reduction
import importlib
try:
    importlib.reload(dimensionality_reduction)
except:
    pass
from dimensionality_reduction import min_max_normalize, normalize_by_column, normalize_by_column_per_subject_wide
feature_cols = [c for c in train_df.columns if c not in ("SubjectID", "EpochID", "label")]

# train_norm_df, test_norm_df = train_df, test_df

# train_norm_df = normalize_by_column_per_subject_wide(train_df, feature_cols)
# test_norm_df = normalize_by_column_per_subject_wide(test_df, feature_cols)

# RUNNING T-TEST - using regression to do the test like named here 
# https://stackoverflow.com/questions/58851008/how-to-perform-student-t-test-in-pyspark

from pyspark.ml.feature import VectorAssembler
from pyspark.ml.regression import LinearRegression

results = []
for feat in feature_cols:
    # Step 1: Assemble the single feature into featuresCol
    assembler = VectorAssembler(inputCols=["label"], outputCol="features")
    assembled = assembler.transform(train_df.select("label", feat).dropna())

    # Step 2: Fit regression model: feature ~ label
    lr = LinearRegression(featuresCol="features", labelCol=feat, regParam=0)
    model = lr.fit(assembled)

    # Step 3: Get t-stat and p-value for 'label'
    summary = model.summary
    t_stat = summary.tValues[1]  # index 1 corresponds to label coefficient
    p_val = summary.pValues[1]

    # Save results
    results.append((feat, t_stat, p_val))




results_df = pd.DataFrame(results, columns=["Feature", "T_statistic", "P_value"])
results_df.sort_values("P_value", inplace=True)  # sort by significance


# add benferroni or FDR correction 
# from statsmodels.stats.multitest import multipletests

# # Apply FDR correction
# rejected, pvals_corrected, _, _ = multipletests(results_df["P_value"], alpha=0.05, method="fdr_bh")
# results_df["FDR_corrected"] = pvals_corrected
# results_df["Significant"] = rejected


# train_norm_df.repartition(16).persist()
# test_norm_df.repartition(16).persist()
print("finished T-test and have results")

25/04/22 03:49:00 WARN Instrumentation: [ec8c051f] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:49:00 WARN InstanceBuilder: Failed to load implementation from:dev.ludovic.netlib.blas.JNIBLAS
25/04/22 03:49:00 WARN InstanceBuilder: Failed to load implementation from:dev.ludovic.netlib.lapack.JNILAPACK
25/04/22 03:49:20 WARN Instrumentation: [8c42f7e3] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:49:40 WARN Instrumentation: [baa2482a] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:50:00 WARN Instrumentation: [318f9444] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:50:19 WARN Instrumentation: [db8e3ddd] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:50:39 WARN Instrumentation: [e2613aa1] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:50:59 WARN Instrumentation: [648f1f9d] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:51:19 WARN Instrumentation: [8d81a5a1] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:51:40 WARN Instrumentation: [4b6af43d] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:52:00 WARN Instrumentation: [498c605e] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:52:20 WARN Instrumentation: [04f61f6b] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:52:40 WARN Instrumentation: [eefdfa20] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:53:00 WARN Instrumentation: [4088143f] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:53:20 WARN Instrumentation: [9e83592c] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:53:40 WARN Instrumentation: [c989fe8b] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:54:00 WARN Instrumentation: [f4bb3ffc] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:54:20 WARN Instrumentation: [ce362b5d] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:54:40 WARN Instrumentation: [8b4e411f] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:55:02 WARN Instrumentation: [b10839b3] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:55:22 WARN Instrumentation: [f2412e8f] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:55:43 WARN Instrumentation: [7eb941e8] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:56:03 WARN Instrumentation: [b4b54c91] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:56:23 WARN Instrumentation: [f376c678] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:56:43 WARN Instrumentation: [aa88a24b] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:57:03 WARN Instrumentation: [576f497d] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:57:24 WARN Instrumentation: [ade9c8c7] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:57:44 WARN Instrumentation: [4edd37ce] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:58:04 WARN Instrumentation: [087d3d78] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:58:24 WARN Instrumentation: [5fe9e493] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:58:45 WARN Instrumentation: [a125fb1a] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:59:05 WARN Instrumentation: [4aef1fb6] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:59:26 WARN Instrumentation: [e88e1f5a] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 03:59:46 WARN Instrumentation: [ecfed29b] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:00:06 WARN Instrumentation: [6623cd0b] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:00:26 WARN Instrumentation: [6ef0f363] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:01:26 WARN Instrumentation: [227e40ff] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:01:45 WARN Instrumentation: [e753fba7] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:02:04 WARN Instrumentation: [a4a8b901] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:02:24 WARN Instrumentation: [b9ecbda1] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:02:44 WARN Instrumentation: [84876bba] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:03:05 WARN Instrumentation: [e1cdbc30] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:03:26 WARN Instrumentation: [d9169e8b] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:03:46 WARN Instrumentation: [b6b76d51] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:04:06 WARN Instrumentation: [8add40bf] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:04:27 WARN Instrumentation: [d87bcaa1] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:04:47 WARN Instrumentation: [11f0402f] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:05:08 WARN Instrumentation: [40e7faba] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:05:28 WARN Instrumentation: [bdfe4fd0] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:05:49 WARN Instrumentation: [bf78a56a] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:06:09 WARN Instrumentation: [5518e859] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:06:30 WARN Instrumentation: [5071e17b] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:06:51 WARN Instrumentation: [58556933] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:07:11 WARN Instrumentation: [5fe3fcc8] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:07:32 WARN Instrumentation: [bbc97752] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:07:53 WARN Instrumentation: [65ba6c7d] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:08:14 WARN Instrumentation: [12fe491f] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:08:34 WARN Instrumentation: [65de706a] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:08:56 WARN Instrumentation: [6ec665ca] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:09:17 WARN Instrumentation: [580f8160] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:09:38 WARN Instrumentation: [bdddee70] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:09:59 WARN Instrumentation: [953211c5] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:10:20 WARN Instrumentation: [33e2e2c7] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:10:41 WARN Instrumentation: [3fa06388] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:11:03 WARN Instrumentation: [ecdd357d] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:11:55 WARN Instrumentation: [e569dbcb] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:12:15 WARN Instrumentation: [fa9ca9aa] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:12:36 WARN Instrumentation: [7f386617] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:12:57 WARN Instrumentation: [9634418a] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:13:18 WARN Instrumentation: [928bce8d] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:13:38 WARN Instrumentation: [472ecc85] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:13:59 WARN Instrumentation: [63a0ed41] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:14:21 WARN Instrumentation: [582761d8] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:14:41 WARN Instrumentation: [7f860458] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:15:03 WARN Instrumentation: [8718f6a7] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:15:23 WARN Instrumentation: [65ad85f7] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:15:44 WARN Instrumentation: [82182d19] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:16:04 WARN Instrumentation: [43acafc5] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:16:28 WARN Instrumentation: [1607d031] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:16:50 WARN Instrumentation: [3055aff6] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:17:11 WARN Instrumentation: [b7d4137a] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:17:32 WARN Instrumentation: [dcc60b99] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:17:54 WARN Instrumentation: [27ee3d95] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:18:15 WARN Instrumentation: [aad3422e] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:18:37 WARN Instrumentation: [09ac27f0] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:18:58 WARN Instrumentation: [5d964f6f] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:19:20 WARN Instrumentation: [7301c1b2] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:19:42 WARN Instrumentation: [ffa097a5] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:20:03 WARN Instrumentation: [c756d634] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:20:25 WARN Instrumentation: [bfc8df81] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:20:48 WARN Instrumentation: [6d81d51a] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:21:09 WARN Instrumentation: [134a2470] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:21:30 WARN Instrumentation: [5a21fea5] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:21:51 WARN Instrumentation: [90bf216a] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:22:46 WARN Instrumentation: [8a1e19c7] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:23:06 WARN Instrumentation: [e166da80] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:23:19 WARN Instrumentation: [96e02901] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:23:29 WARN Instrumentation: [5aafde06] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:23:39 WARN Instrumentation: [1dfcf6c5] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:23:50 WARN Instrumentation: [6b3bc356] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:24:00 WARN Instrumentation: [5aea740d] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:24:10 WARN Instrumentation: [c372155b] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:24:20 WARN Instrumentation: [5455bb82] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:24:31 WARN Instrumentation: [14438e25] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:24:41 WARN Instrumentation: [84b1b2b5] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:24:51 WARN Instrumentation: [1d262b8e] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:25:02 WARN Instrumentation: [305c6557] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:25:12 WARN Instrumentation: [d8b34f40] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:25:23 WARN Instrumentation: [6459d1e4] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:25:33 WARN Instrumentation: [ae077d94] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:25:44 WARN Instrumentation: [21b74e5a] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:25:55 WARN Instrumentation: [538d21bf] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:26:05 WARN Instrumentation: [be3516ea] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:26:16 WARN Instrumentation: [85b0c11e] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:26:26 WARN Instrumentation: [dec0f03e] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:26:37 WARN Instrumentation: [c5c99c4e] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:26:48 WARN Instrumentation: [d638398d] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:26:59 WARN Instrumentation: [48383662] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:27:09 WARN Instrumentation: [98a58dad] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:27:20 WARN Instrumentation: [a6672b7f] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:27:32 WARN Instrumentation: [594e4f29] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:27:43 WARN Instrumentation: [f3d73c64] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:27:54 WARN Instrumentation: [8f0ff00c] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:28:06 WARN Instrumentation: [7312bffb] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:28:17 WARN Instrumentation: [8d21d6df] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:28:27 WARN Instrumentation: [5c41667e] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:28:38 WARN Instrumentation: [7b4c6d95] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:28:49 WARN Instrumentation: [969a614b] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:28:59 WARN Instrumentation: [3e9a6fd8] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:29:10 WARN Instrumentation: [dbdf9288] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:29:21 WARN Instrumentation: [eb065739] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:29:32 WARN Instrumentation: [5442a314] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:29:42 WARN Instrumentation: [17856619] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:29:53 WARN Instrumentation: [ae617355] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:30:03 WARN Instrumentation: [691b1c19] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:30:12 WARN Instrumentation: [f3b90a46] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:30:22 WARN Instrumentation: [25044978] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:30:31 WARN Instrumentation: [a19cd548] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:30:41 WARN Instrumentation: [cf847bc1] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:30:50 WARN Instrumentation: [d0d78bbe] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:31:00 WARN Instrumentation: [f83b8fbd] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:31:09 WARN Instrumentation: [40866908] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:31:18 WARN Instrumentation: [467d88a3] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:31:28 WARN Instrumentation: [107c40c9] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:31:37 WARN Instrumentation: [3f599195] regParam is zero, which might cause numerical instability and overfitting.
25/04/22 04:31:46 WARN Instrumentation: [86a687d1] regParam is zero, which might cause numerical instability and overfitting.
[Stage 15747:====================================>                (11 + 5) / 16]

finished T-test and have results

In [60]:
# train_norm_df.head(1)
results_df

               Feature  T_statistic       P_value
0       C3_Alpha_Power   288.468797  0.000000e+00
92      T6_Delta_Power  2076.905380  0.000000e+00
93      T6_Theta_Power   354.318054  0.000000e+00
94    T6_custom1_Power   304.516987  0.000000e+00
95      C3_TotalEnergy   555.989794  0.000000e+00
..                 ...          ...           ...
50      O1_Alpha_Power   342.040467  0.000000e+00
51       O1_Beta_Power   333.024402  0.000000e+00
44   Fp2_custom1_Power   282.998859  0.000000e+00
144           Variance    23.070079  0.000000e+00
139               Mean     7.162633  7.946976e-13

[145 rows x 3 columns]

In [66]:
results_df = results_df.sort_values(by="T_statistic", ascending=False)

In [67]:
results_df

            Feature   T_statistic       P_value
112  Fp2_TotalPower  2.659947e+18  0.000000e+00
104   F4_TotalPower  2.659947e+18  0.000000e+00
110  Fp1_TotalPower  2.659947e+18  0.000000e+00
116   O1_TotalPower  2.659947e+18  0.000000e+00
114   Fz_TotalPower  2.659947e+18  0.000000e+00
..              ...           ...           ...
26    F7_Beta_Power  2.330696e+02  0.000000e+00
138        Kurtosis  2.145451e+02  0.000000e+00
142        Skewness  3.284406e+01  0.000000e+00
144        Variance  2.307008e+01  0.000000e+00
139            Mean  7.162633e+00  7.946976e-13

[145 rows x 3 columns]

In [57]:
results_df.to_pickle("ttest_results.pkl")

In [68]:
from pyspark.sql.functions import col, avg, stddev, count

cohen_d_results = []

for feat in feature_cols:
    stats = (
        train_df
        .select("label", feat)
        .dropna()
        .groupBy("label")
        .agg(
            avg(feat).alias("mean"),
            stddev(feat).alias("std"),
            count(feat).alias("n")
        )
        .toPandas()
        .set_index("label")
    )
    
    if 0 in stats.index and 1 in stats.index:
        mean0 = stats.loc[0, "mean"]
        mean1 = stats.loc[1, "mean"]
        std0 = stats.loc[0, "std"]
        std1 = stats.loc[1, "std"]
        n0 = stats.loc[0, "n"]
        n1 = stats.loc[1, "n"]

        # pooled std
        pooled_std = (( (n0 - 1) * std0**2 + (n1 - 1) * std1**2 ) / (n0 + n1 - 2)) ** 0.5
        cohen_d = (mean1 - mean0) / pooled_std if pooled_std > 0 else 0.0
    else:
        cohen_d = None

    cohen_d_results.append((feat, cohen_d))

                                                                                 1000]]

In [72]:
# cohen_d_results.to_csv("cohen_results.csv")

AttributeError: 'list' object has no attribute 'to_csv'

In [73]:
cohen_d_results

[('C3_Alpha_Power', np.float64(-0.21389868181812077)),
 ('C3_Beta_Power', np.float64(-0.08392950087128903)),
 ('C3_Delta_Power', np.float64(0.07323232802178882)),
 ('C3_Theta_Power', np.float64(0.03550408497543001)),
 ('C3_custom1_Power', np.float64(-0.2281871926421838)),
 ('C4_Alpha_Power', np.float64(-0.1946917102011591)),
 ('C4_Beta_Power', np.float64(-0.08781034680931392)),
 ('C4_Delta_Power', np.float64(0.06814180387932797)),
 ('C4_Theta_Power', np.float64(0.036558662770668375)),
 ('C4_custom1_Power', np.float64(-0.2151602247442516)),
 ('Cz_Alpha_Power', np.float64(-0.19874901428754202)),
 ('Cz_Beta_Power', np.float64(-0.06835259814889932)),
 ('Cz_Delta_Power', np.float64(0.06473067996992257)),
 ('Cz_Theta_Power', np.float64(0.024046620763203574)),
 ('Cz_custom1_Power', np.float64(-0.21863213422617675)),
 ('F3_Alpha_Power', np.float64(-0.3070683644303182)),
 ('F3_Beta_Power', np.float64(-0.07948873769540932)),
 ('F3_Delta_Power', np.float64(0.031258158510748944)),
 ('F3_Theta_Power', np.float64(0.18374424126608205)),
 ('F3_custom1_Power', np.float64(-0.33964819031190707)),
 ('F4_Alpha_Power', np.float64(-0.3941818014918262)),
 ('F4_Beta_Power', np.float64(-0.052587696639495356)),
 ('F4_Delta_Power', np.float64(0.0762020302757123)),
 ('F4_Theta_Power', np.float64(0.1471628086012131)),
 ('F4_custom1_Power', np.float64(-0.4237697621767051)),
 ('F7_Alpha_Power', np.float64(-0.3085842944906674)),
 ('F7_Beta_Power', np.float64(-0.012549510292562136)),
 ('F7_Delta_Power', np.float64(0.02109592173288962)),
 ('F7_Theta_Power', np.float64(0.1866801999447701)),
 ('F7_custom1_Power', np.float64(-0.36082825407386787)),
 ('F8_Alpha_Power', np.float64(-0.3746411604754874)),
 ('F8_Beta_Power', np.float64(-0.037611469671147806)),
 ('F8_Delta_Power', np.float64(0.07550339238704154)),
 ('F8_Theta_Power', np.float64(0.15097841712844715)),
 ('F8_custom1_Power', np.float64(-0.41985081504734423)),
 ('Fp1_Alpha_Power', np.float64(-0.4311968351883602)),
 ('Fp1_Beta_Power', np.float64(-0.19901680552251813)),
 ('Fp1_Delta_Power', np.float64(0.1628438024918923)),
 ('Fp1_Theta_Power', np.float64(0.14485350981200323)),
 ('Fp1_custom1_Power', np.float64(-0.4663826889010972)),
 ('Fp2_Alpha_Power', np.float64(-0.44962559786652395)),
 ('Fp2_Beta_Power', np.float64(-0.10901437038638126)),
 ('Fp2_Delta_Power', np.float64(0.1406908460561713)),
 ('Fp2_Theta_Power', np.float64(0.140911837549594)),
 ('Fp2_custom1_Power', np.float64(-0.484448430122147)),
 ('Fz_Alpha_Power', np.float64(-0.37759774017219555)),
 ('Fz_Beta_Power', np.float64(-0.13031347705329033)),
 ('Fz_Delta_Power', np.float64(0.07483655744125035)),
 ('Fz_Theta_Power', np.float64(0.18408288761739006)),
 ('Fz_custom1_Power', np.float64(-0.395434711663619)),
 ('O1_Alpha_Power', np.float64(-0.7309058995762372)),
 ('O1_Beta_Power', np.float64(-0.2512266593623062)),
 ('O1_Delta_Power', np.float64(0.5003191954466503)),
 ('O1_Theta_Power', np.float64(0.12948043379232685)),
 ('O1_custom1_Power', np.float64(-0.6735719573634046)),
 ('O2_Alpha_Power', np.float64(-0.8227230717718071)),
 ('O2_Beta_Power', np.float64(-0.3433294400230223)),
 ('O2_Delta_Power', np.float64(0.6000474532968132)),
 ('O2_Theta_Power', np.float64(0.12629347830065463)),
 ('O2_custom1_Power', np.float64(-0.7748669303449427)),
 ('P3_Alpha_Power', np.float64(-0.5696116646666974)),
 ('P3_Beta_Power', np.float64(-0.233379552627378)),
 ('P3_Delta_Power', np.float64(0.3160790730979131)),
 ('P3_Theta_Power', np.float64(0.08207258790605516)),
 ('P3_custom1_Power', np.float64(-0.5789668420554391)),
 ('P4_Alpha_Power', np.float64(-0.4557629540733389)),
 ('P4_Beta_Power', np.float64(-0.19088227622798976)),
 ('P4_Delta_Power', np.float64(0.22192223599886554)),
 ('P4_Theta_Power', np.float64(0.10172077632095435)),
 ('P4_custom1_Power', np.float64(-0.4796033290173806)),
 ('Pz_Alpha_Power', np.float64(-0.5258675676543644)),
 ('Pz_Beta_Power', np.float64(-0.18874242661007726)),
 ('Pz_Delta_Power', np.float64(0.27348108158479484)),
 ('Pz_Theta_Power', np.float64(0.072320790191615)),
 ('Pz_custom1_Power', np.float64(-0.5462381700626311)),
 ('T3_Alpha_Power', np.float64(-0.3846395420398011)),
 ('T3_Beta_Power', np.float64(-0.21665928038158472)),
 ('T3_Delta_Power', np.float64(0.13619284716429594)),
 ('T3_Theta_Power', np.float64(0.17976783591416268)),
 ('T3_custom1_Power', np.float64(-0.42123926215875546)),
 ('T4_Alpha_Power', np.float64(-0.32227339034172486)),
 ('T4_Beta_Power', np.float64(-0.038376862579983836)),
 ('T4_Delta_Power', np.float64(0.05022100451338733)),
 ('T4_Theta_Power', np.float64(0.1484006307666013)),
 ('T4_custom1_Power', np.float64(-0.36241816711632374)),
 ('T5_Alpha_Power', np.float64(-0.7635024702216959)),
 ('T5_Beta_Power', np.float64(-0.33455826530190474)),
 ('T5_Delta_Power', np.float64(0.5216469257445111)),
 ('T5_Theta_Power', np.float64(0.1334303877064145)),
 ('T5_custom1_Power', np.float64(-0.7216417856328037)),
 ('T6_Alpha_Power', np.float64(-0.6400288141203109)),
 ('T6_Beta_Power', np.float64(-0.23371964956583735)),
 ('T6_Delta_Power', np.float64(0.36639462999637135)),
 ('T6_Theta_Power', np.float64(0.16222440311443717)),
 ('T6_custom1_Power', np.float64(-0.6397647371768435)),
 ('C3_TotalEnergy', np.float64(0.007644872122744657)),
 ('C3_TotalPower', 0.0),
 ('C4_TotalEnergy', np.float64(0.010705904236218023)),
 ('C4_TotalPower', 0.0),
 ('Cz_TotalEnergy', np.float64(0.011685894134215388)),
 ('Cz_TotalPower', 0.0),
 ('F3_TotalEnergy', np.float64(-0.08875681199605019)),
 ('F3_TotalPower', 0.0),
 ('F4_TotalEnergy', np.float64(-0.056278940396058325)),
 ('F4_TotalPower', 0.0),
 ('F7_TotalEnergy', np.float64(-0.06892931659508725)),
 ('F7_TotalPower', 0.0),
 ('F8_TotalEnergy', np.float64(-0.04263581554108199)),
 ('F8_TotalPower', 0.0),
 ('Fp1_TotalEnergy', np.float64(-0.030274501445739052)),
 ('Fp1_TotalPower', 0.0),
 ('Fp2_TotalEnergy', np.float64(-0.023678665315823803)),
 ('Fp2_TotalPower', 0.0),
 ('Fz_TotalEnergy', np.float64(-0.006935756343126094)),
 ('Fz_TotalPower', 0.0),
 ('O1_TotalEnergy', np.float64(0.12868010481616063)),
 ('O1_TotalPower', 0.0),
 ('O2_TotalEnergy', np.float64(0.17678126449761225)),
 ('O2_TotalPower', 0.0),
 ('P3_TotalEnergy', np.float64(0.07902779923400023)),
 ('P3_TotalPower', 0.0),
 ('P4_TotalEnergy', np.float64(0.05247496660451363)),
 ('P4_TotalPower', 0.0),
 ('Pz_TotalEnergy', np.float64(0.06376047611905362)),
 ('Pz_TotalPower', 0.0),
 ('T3_TotalEnergy', np.float64(-0.00667060356517353)),
 ('T3_TotalPower', 0.0),
 ('T4_TotalEnergy', np.float64(-0.04174042589662674)),
 ('T4_TotalPower', 0.0),
 ('T5_TotalEnergy', np.float64(0.15134741428036116)),
 ('T5_TotalPower', 0.0),
 ('T6_TotalEnergy', np.float64(0.06277883636269219)),
 ('T6_TotalPower', 0.0),
 ('AppEntropy', np.float64(0.2825535735113496)),
 ('HiguchiFD', np.float64(0.4107658371857342)),
 ('HjorthComplexity', np.float64(-0.17847411074573727)),
 ('HjorthMobility', np.float64(0.16572176548623657)),
 ('KatzFD', np.float64(0.14841944177020186)),
 ('Kurtosis', np.float64(0.009483466996379893)),
 ('Mean', np.float64(-0.036895855546787294)),
 ('RMS', np.float64(0.0351761108381606)),
 ('SampleEntropy', np.float64(0.29841445247669374)),
 ('Skewness', np.float64(-0.0012612611848860093)),
 ('Std', np.float64(0.03517611088159729)),
 ('Variance', np.float64(0.05774284940572363))]

In [56]:
import os
os.system('say "t-test is done!"')

0

In [74]:
cohen_df = pd.DataFrame(cohen_d_results, columns=["Feature", "Cohen_d"])
results_df = results_df.merge(cohen_df, on="Feature")
results_df["Abs_Cohen_d"] = results_df["Cohen_d"].abs()

In [80]:
results_df = results_df.sort_values(by="Abs_Cohen_d", ascending=False)

In [81]:
results_df

              Feature   T_statistic  P_value   Cohen_d  Abs_Cohen_d
68     O2_Alpha_Power  3.662162e+02      0.0 -0.822723     0.822723
95   O2_custom1_Power  3.162845e+02      0.0 -0.774867     0.774867
82     T5_Alpha_Power  3.478615e+02      0.0 -0.763502     0.763502
86     O1_Alpha_Power  3.420405e+02      0.0 -0.730906     0.730906
107  T5_custom1_Power  2.998276e+02      0.0 -0.721642     0.721642
..                ...           ...      ...       ...          ...
5       P4_TotalPower  2.659947e+18      0.0  0.000000     0.000000
3       O1_TotalPower  2.659947e+18      0.0  0.000000     0.000000
2      Fp1_TotalPower  2.659947e+18      0.0  0.000000     0.000000
7       Pz_TotalPower  2.659947e+18      0.0  0.000000     0.000000
8       F8_TotalPower  2.659947e+18      0.0  0.000000     0.000000

[145 rows x 5 columns]

In [82]:
results_df.to_pickle("ttest+cohen_results.pkl")
results_df.to_csv("ttest+cohen_results.csv")

In [ ]:
import importlib
try:
    importlib.reload(dimensionality_reduction)
except:
    pass
from dimensionality_reduction import apply_pca_model

# train_df = apply_pca_model(train_norm_df, pca_input_cols, pca_model, k_val)
# test_df = apply_pca_model(test_norm_df, pca_input_cols, pca_model, k_val)

In [ ]:
train_df

In [ ]:
import importlib
try:
    importlib.reload(dimensionality_reduction)
except:
    pass
    
from dimensionality_reduction import min_max_normalize, normalize_by_column, normalize_by_column_per_subject_wide

# train_df = normalize_by_column_per_subject_wide(train_df, feature_cols)
# test_df = normalize_by_column_per_subject_wide(test_df, feature_cols)

In [ ]:
print("got here")

# ML time

In [ ]:
train_df.head(1)

In [ ]:
train_df.columns

In [ ]:
import importlib
try:
    importlib.reload(dimensionality_reduction)
except:
    pass
importlib.reload(dimensionality_reduction)
from dimensionality_reduction import min_max_normalize_post_pca_by_subject

train_df = min_max_normalize_post_pca_by_subject(train_df)
test_df = min_max_normalize_post_pca_by_subject(test_df)

In [ ]:
train_df.head(1)

In [ ]:
train_pd = train_df.toPandas()
test_pd = test_df.toPandas()
# spark.stop()

In [ ]:
import numpy as np

# Convert Spark DenseVectors to regular 2D numpy arrays
X_train = np.array(train_pd["features"].tolist())
y_train = train_pd["label"].values

X_test = np.array(test_pd["features"].tolist())
y_test = test_pd["label"].values

In [ ]:
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)

In [ ]:
y_train

In [ ]:
X_train

In [ ]:
# How can we do standard scaler per subject ! !!!  ! ! ! !  !  !! ! !  !

In [ ]:
print("work")

In [ ]:
from sklearn.preprocessing import StandardScaler


X_train_scaled = X_train

X_test_scaled = X_test

# making sure min-maxed ! also might change results a little 

# scaler = StandardScaler()

# X_train_scaled = scaler.fit_transform(X_train)

# X_test_scaled = scaler.transform(X_test)

In [ ]:
%%time
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import StandardScaler
import numpy as np
import time

# # Step 1: Scale once
# scaler = StandardScaler()
# X_train_scaled = scaler.fit_transform(X_train)
# X_test_scaled = scaler.transform(X_test)

# Step 2: Define hyperparameter grid
k_values = [1, 2, 3, 5, 7, 9, 11]
weights_list = ['uniform', 'distance']
metrics = ['euclidean', 'manhattan']
p_values = [1, 2]  # Only used if metric is 'minkowski'

# Step 3: Set up result tracking
results = []
target_names = ["Control", "Alzheimer's"]
print("start")

# Step 4: Manual hyperparameter search
for k in k_values:
    for weight in weights_list:
        for metric in metrics:
            for p in p_values:

                if metric != 'minkowski' and p != 2:
                    continue  # p is irrelevant unless using 'minkowski'

                label = f"KNN k={k}, weight={weight}, metric={metric}, p={p}"
                model = KNeighborsClassifier(
                    n_neighbors=k,
                    weights=weight,
                    metric=metric if metric != 'minkowski' else 'minkowski',
                    p=p
                )

                print(f"\n=== Cross-Validation: {label} ===")
                start = time.time()

                # Step 5: Cross-validation scores
                scores = cross_val_score(model, X_train_scaled, y_train, cv=15, scoring='accuracy', n_jobs=3)
                mean_acc, std_acc = scores.mean(), scores.std()
                print(f"Mean Accuracy: {mean_acc:.4f}")
                print(f"Std Deviation: {std_acc:.4f}")
                print(f"All Fold Scores: {np.round(scores, 4)}")

                # Step 6: Best fold evaluation
                skf = StratifiedKFold(n_splits=15, shuffle=True, random_state=42)
                best_fold_index = np.argmax(scores)
                for i, (train_idx, test_idx) in enumerate(skf.split(X_train_scaled, y_train)):
                    if i == best_fold_index:
                        X_tr, X_te = X_train_scaled[train_idx], X_train_scaled[test_idx]
                        y_tr, y_te = y_train[train_idx], y_train[test_idx]

                        model.fit(X_tr, y_tr)
                        y_pred_test = model.predict(X_te)
                        y_pred_train = model.predict(X_tr)

                        train_acc = accuracy_score(y_tr, y_pred_train)
                        val_acc = accuracy_score(y_te, y_pred_test)

                        print(f"\n=== Best Fold Summary: {label} ===")
                        print(f"Train Accuracy: {train_acc:.4f}")
                        print(f"Validation Accuracy: {val_acc:.4f}")
                        print(classification_report(y_te, y_pred_test, target_names=target_names))

                        # Step 7: Evaluate on the held-out test set
                        #!! shouldn't we be testing oin the model that is trained on all the folds 1 by 1 (so multiple epochs) ?
                        model.fit(X_train_scaled, y_train)
                        y_test_pred = model.predict(X_test_scaled)
                        test_acc = accuracy_score(y_test, y_test_pred)
                        print(f"Test Accuracy: {test_acc:.4f}")
                        print(classification_report(y_test, y_test_pred, target_names=target_names))

                        results.append((label, mean_acc, std_acc, train_acc, val_acc, test_acc))
                        break

                print(f"⏱️ Duration: {time.time() - start:.1f}s")

# Step 8: Final summary sorted by CV accuracy
results.sort(key=lambda x: x[1], reverse=True)
print("\n=== Top Models by Mean CV Accuracy ===")
for label, mean_acc, std_acc, train_acc, val_acc, test_acc in results:
    print(f"{label:<65} -> CV: {mean_acc:.4f} ± {std_acc:.4f} | Train: {train_acc:.4f} | Validation: {val_acc:.4f} | Test: {test_acc:.4f}")

In [ ]:
%%time
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import time

# Step 1: Scale data once (IMPORTANT: transform X_test with same scaler)
scaler = MinMaxScaler(feature_range=(-1, 1))
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Step 2: Hyperparameters
layer_configs = [(256, 128, 64), (128, 64, 16)]
activations = ['relu']
alphas = [1e-6, 1e-5, 1e-4, 1e-3, 1e-2, 1e-1, 5e-1, 1.0]
early_stopping_options = [True, False]
max_iter = 30000

# Step 3: Set up result tracking
results = []
target_names = ["Control", "Alzheimer's"]

# Step 4: Brute-force hyperparameter loop
for layers in layer_configs:
    for activation in activations:
        for alpha in alphas:
            for early_stopping in early_stopping_options:

                label = f"MLP {layers}, act={activation}, alpha={alpha}, early_stop={early_stopping}, max_iter={max_iter}"
                model = MLPClassifier(
                    hidden_layer_sizes=layers,
                    activation=activation,
                    alpha=alpha,
                    early_stopping=early_stopping,
                    max_iter=max_iter,
                    random_state=42,
                )

                print(f"\n=== Cross-Validation: {label} ===")
                start = time.time()

                # Step 5: Cross-validation
                scores = cross_val_score(model, X_train_scaled, y_train, cv=5, scoring='accuracy', n_jobs=3)
                mean_acc, std_acc = scores.mean(), scores.std()
                print(f"Mean Accuracy: {mean_acc:.4f}")
                print(f"Std Deviation: {std_acc:.4f}")
                print(f"All Fold Scores: {np.round(scores, 4)}")

                # Step 6: Evaluate on best validation fold
                skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
                best_fold_index = np.argmax(scores)
                for i, (train_idx, test_idx) in enumerate(skf.split(X_train_scaled, y_train)):
                    if i == best_fold_index:
                        X_tr, X_te = X_train_scaled[train_idx], X_train_scaled[test_idx]
                        y_tr, y_te = y_train[train_idx], y_train[test_idx]

                        model.fit(X_tr, y_tr)
                        y_pred_test = model.predict(X_te)
                        y_pred_train = model.predict(X_tr)

                        train_acc = accuracy_score(y_tr, y_pred_train)
                        val_acc = accuracy_score(y_te, y_pred_test)

                        print(f"\n=== Best Fold Summary: {label} ===")
                        print(f"Train Accuracy: {train_acc:.4f}")
                        print(f"Validation Accuracy: {val_acc:.4f}")
                        print(classification_report(y_te, y_pred_test, target_names=target_names))

                        break

                # Step 7: Evaluate on held-out test set
                model.fit(X_train_scaled, y_train)
                y_test_pred = model.predict(X_test_scaled)
                test_acc = accuracy_score(y_test, y_test_pred)
                print(f"\n=== Final Test Set Evaluation: {label} ===")
                print(f"Test Accuracy: {test_acc:.4f}")
                print(classification_report(y_test, y_test_pred, target_names=target_names))

                results.append((label, mean_acc, std_acc, train_acc, val_acc, test_acc))

                print(f"⏱️ Duration: {time.time() - start:.1f}s")

# Step 8: Print final summary
results.sort(key=lambda x: x[1], reverse=True)
print("\n=== Top Models by Mean CV Accuracy ===")
for label, mean_acc, std_acc, train_acc, val_acc, test_acc in results:
    print(f"{label:<75} -> CV: {mean_acc:.4f} ± {std_acc:.4f} | Train: {train_acc:.4f} | Validation: {val_acc:.4f} | Test: {test_acc:.4f}")

In [ ]:
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.metrics import classification_report, accuracy_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier, BaggingClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
import numpy as np

# Define models
models = {
    # "KNN-tuned": KNeighborsClassifier(
    #     n_neighbors=3,
    #     weights='distance',
    #     metric='euclidean',
    #     p=1
    # ),
    # "KNN": KNeighborsClassifier(),
    # "NeuralNet": MLPClassifier(hidden_layer_sizes=(100,), max_iter=10000, random_state=42),
    "DecisionTree": DecisionTreeClassifier(
        max_depth=8,
        max_features=None,
        min_samples_leaf=10,
        min_samples_split=5,
        random_state=42
    ),
    "GradientBoostedTrees": GradientBoostingClassifier(n_estimators=100, random_state=42),
    "BaggedSVM": make_pipeline(
        BaggingClassifier(
            estimator=SVC(kernel='linear', probability=False),
            n_estimators=10,
            max_samples=0.1,
            n_jobs=3,
            bootstrap=False,
            random_state=42
        )
    ),
    "SVM": make_pipeline(
        SVC(kernel='linear', probability=True)
    )
}

# Run 15-fold CV with parallelization
for name, model in models.items():
    print(f"\n=== Cross-Validation: {name} ===")
    
    # Cross-validation scores
    scores = cross_val_score(model, X_train, y_train, cv=15, scoring='accuracy', n_jobs=-1)
    
    print(f"Mean Accuracy: {scores.mean():.4f}")
    print(f"Standard Deviation: {scores.std():.4f}")
    print(f"All Fold Scores: {np.round(scores, 4)}")
    
    # Get predictions from best-performing fold
    best_fold_index = np.argmax(scores)
    
    # Refit on best 14/15 folds and evaluate on the 1/15
    skf = StratifiedKFold(n_splits=15, shuffle=True, random_state=42)
    for i, (train_index, test_index) in enumerate(skf.split(X_train, y_train)):
        if i == best_fold_index:
            X_tr, X_te = X_train[train_index], X_train[test_index]
            y_tr, y_te = y_train[train_index], y_train[test_index]
            
            model.fit(X_tr, y_tr)
            y_pred_test = model.predict(X_te)
            y_pred_train = model.predict(X_tr)

            val_acc = accuracy_score(y_te, y_pred_test)
            train_acc = accuracy_score(y_tr, y_pred_train)

            print(f"\n=== Best Fold Summary: {name} ===")
            print(f"Train Accuracy: {train_acc:.4f}")
            print(f"Validation Accuracy: {val_acc:.4f}")
            print(classification_report(y_te, y_pred_test, target_names=["Control", "Alzheimer's"]))
            break

    # Final evaluation on the held-out test set
    model.fit(X_train, y_train)
    y_test_pred = model.predict(X_test)
    test_acc = accuracy_score(y_test, y_test_pred)
    print(f"\n=== Test Set Evaluation: {name} ===")
    print(f"Test Accuracy: {test_acc:.4f}")
    print(classification_report(y_test, y_test_pred, target_names=["Control", "Alzheimer's"]))

In [ ]:
%%time
from sklearn.ensemble import BaggingClassifier
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.metrics import accuracy_score, classification_report
import numpy as np
import time

# Step 1: Scale data for SVMs
scaler = StandardScaler()
X_train_svm = scaler.fit_transform(X_train)
X_test_svm = scaler.transform(X_test)

# Step 2: Define hyperparameter grids
C_values = [0.01, 0.1, 1, 10]
n_estimators_list = [5, 10, 20]
max_samples_list = [0.1, 0.5, 1.0]
bootstrap_options = [False, True]

# Step 3: Track results
results = []
target_names = ["Control", "Alzheimer's"]

# Step 4: Hyperparameter tuning
for C in C_values:
    for n_est in n_estimators_list:
        for max_samp in max_samples_list:
            for bootstrap in bootstrap_options:
                
                label = f"BaggedSVM C={C}, est={n_est}, max_samples={max_samp}, bootstrap={bootstrap}"
                model = make_pipeline(
                    BaggingClassifier(
                        estimator=SVC(C=C, kernel='linear', probability=False),
                        n_estimators=n_est,
                        max_samples=max_samp,
                        bootstrap=bootstrap,
                        n_jobs=3,
                        random_state=42
                    )
                )

                print(f"\n=== Cross-Validation: {label} ===")
                start = time.time()

                scores = cross_val_score(model, X_train_svm, y_train, cv=5, scoring='accuracy', n_jobs=3)
                mean_acc, std_acc = scores.mean(), scores.std()
                print(f"Mean Accuracy: {mean_acc:.4f}")
                print(f"Std Deviation: {std_acc:.4f}")
                print(f"All Fold Scores: {np.round(scores, 4)}")

                # Best fold deep dive
                skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
                best_fold_index = np.argmax(scores)
                for i, (train_idx, val_idx) in enumerate(skf.split(X_train_svm, y_train)):
                    if i == best_fold_index:
                        X_tr, X_val = X_train_svm[train_idx], X_train_svm[val_idx]
                        y_tr, y_val = y_train[train_idx], y_train[val_idx]

                        model.fit(X_tr, y_tr)
                        y_pred_val = model.predict(X_val)
                        y_pred_train = model.predict(X_tr)

                        train_acc = accuracy_score(y_tr, y_pred_train)
                        val_acc = accuracy_score(y_val, y_pred_val)

                        print(f"\n=== Best Fold Summary: {label} ===")
                        print(f"Train Accuracy: {train_acc:.4f}")
                        print(f"Validation Accuracy: {val_acc:.4f}")
                        print(classification_report(y_val, y_pred_val, target_names=target_names))

                        break

                # Final test set evaluation
                model.fit(X_train_svm, y_train)
                y_test_pred = model.predict(X_test_svm)
                test_acc = accuracy_score(y_test, y_test_pred)

                print(f"\n=== Test Set Evaluation: {label} ===")
                print(f"Test Accuracy: {test_acc:.4f}")
                print(classification_report(y_test, y_test_pred, target_names=target_names))

                results.append((label, mean_acc, std_acc, train_acc, val_acc, test_acc))

                print(f"⏱️ Duration: {time.time() - start:.1f}s")

# Step 5: Print top models
results.sort(key=lambda x: x[1], reverse=True)
print("\n=== Top Models by Mean CV Accuracy ===")
for label, mean_acc, std_acc, train_acc, val_acc, test_acc in results:
    print(f"{label:<90} -> CV: {mean_acc:.4f} ± {std_acc:.4f} | Train: {train_acc:.4f} | Val: {val_acc:.4f} | Test: {test_acc:.4f}")

In [ ]:
%%time
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.metrics import accuracy_score, classification_report
import numpy as np
import time

# Step 1: No need to scale for trees
X_train_tree = X_train
X_test_tree = X_test

# Step 2: More complex hyperparameter grid
max_depths = [10, 15, 20, None]  # None = fully grow the tree
min_samples_splits = [2, 3, 5]   # Smaller split thresholds
min_samples_leafs = [1, 2]       # Smaller leaves allowed

# Step 3: Set up result tracking
results = []
target_names = ["Control", "Alzheimer's"]

# Step 4: Manual hyperparameter search
for depth in max_depths:
    for min_split in min_samples_splits:
        for min_leaf in min_samples_leafs:

            label = f"DecisionTree max_depth={depth}, min_split={min_split}, min_leaf={min_leaf}"
            model = DecisionTreeClassifier(
                max_depth=depth,
                min_samples_split=min_split,
                min_samples_leaf=min_leaf,
                max_features=None,  # use all features
                ccp_alpha=0.0,      # disable pruning
                random_state=42
            )

            print(f"\n=== Cross-Validation: {label} ===")
            start = time.time()

            # Step 5: Cross-validation scores
            scores = cross_val_score(model, X_train_tree, y_train, cv=5, scoring='accuracy', n_jobs=3)
            mean_acc, std_acc = scores.mean(), scores.std()
            print(f"Mean Accuracy: {mean_acc:.4f}")
            print(f"Std Deviation: {std_acc:.4f}")
            print(f"All Fold Scores: {np.round(scores, 4)}")

            # Step 6: Best fold evaluation
            skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
            best_fold_index = np.argmax(scores)
            for i, (train_idx, test_idx) in enumerate(skf.split(X_train_tree, y_train)):
                if i == best_fold_index:
                    X_tr, X_te = X_train_tree[train_idx], X_train_tree[test_idx]
                    y_tr, y_te = y_train[train_idx], y_train[test_idx]

                    model.fit(X_tr, y_tr)
                    y_pred_test = model.predict(X_te)
                    y_pred_train = model.predict(X_tr)

                    train_acc = accuracy_score(y_tr, y_pred_train)
                    test_acc = accuracy_score(y_te, y_pred_test)

                    print(f"\n=== Best Fold Summary: {label} ===")
                    print(f"Train Accuracy: {train_acc:.4f}")
                    print(f"Test Accuracy: {test_acc:.4f}")
                    print(classification_report(y_te, y_pred_test, target_names=target_names))

                    results.append((label, mean_acc, std_acc, train_acc, test_acc))
                    break

            print(f"⏱️ Duration: {time.time() - start:.1f}s")

# Step 7: Final summary sorted by CV accuracy
results.sort(key=lambda x: x[1], reverse=True)
print("\n=== Top Models by Mean CV Accuracy ===")
for label, mean_acc, std_acc, train_acc, test_acc in results:
    print(f"{label:<75} -> CV: {mean_acc:.4f} ± {std_acc:.4f} | Train: {train_acc:.4f} | Test: {test_acc:.4f}")

In [ ]:
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.metrics import classification_report, accuracy_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier, BaggingClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
import numpy as np


# Define models
models = { # NEED TO GO THORUGH AND MAKE SURE DEFAULTS ARE OK, SHOULD NOT HAVE HAD STANDARD SCALER FOR SVM'S
    # "KNN-tuned": KNeighborsClassifier(
    # n_neighbors=3,
    # weights='distance',
    # metric='euclidean',
    # p=1
    # ),
    # "KNN": KNeighborsClassifier(),
    # "NeuralNet": MLPClassifier(hidden_layer_sizes=(100,), max_iter=10000, random_state=42),
    "DecisionTree": DecisionTreeClassifier(
        max_depth=8,
        max_features=None,
        min_samples_leaf=10,
        min_samples_split=5,
        random_state=42
    ),
    "GradientBoostedTrees": GradientBoostingClassifier(n_estimators=100, random_state=42),
        # Faster ensemble of SVMs
    "BaggedSVM": make_pipeline(
        # StandardScaler(),
        BaggingClassifier(
            estimator=SVC(kernel='linear', probability=False),
            n_estimators=10,
            max_samples=0.1,
            n_jobs=3,
            bootstrap=False,
            random_state=42
        )
    ),

    # Classic SVM (can be slow on big data)
    "SVM": make_pipeline(
        # StandardScaler(), 
        SVC(kernel='linear',
        probability=True)
    )
}

from sklearn.model_selection import StratifiedKFold

# Run 15-fold CV with parallelization
for name, model in models.items():
    print(f"\n=== Cross-Validation: {name} ===")
    
    # Cross-validation scores
    scores = cross_val_score(model, X_train, y_train, cv=15, scoring='accuracy', n_jobs=-1)
    
    print(f"Mean Accuracy: {scores.mean():.4f}")
    print(f"Standard Deviation: {scores.std():.4f}")
    print(f"All Fold Scores: {np.round(scores, 4)}")
    
    # Get predictions from best-performing fold
    best_fold_index = np.argmax(scores)
    
    # Refit on best 14/15 folds and evaluate on the 1/15
    skf = StratifiedKFold(n_splits=15, shuffle=True, random_state=42)
    for i, (train_index, test_index) in enumerate(skf.split(X_train, y_train)):
        if i == best_fold_index:
            X_tr, X_te = X_train[train_index], X_train[test_index]
            y_tr, y_te = y_train[train_index], y_train[test_index]
            
            model.fit(X_tr, y_tr)
            y_pred_test = model.predict(X_te)
            y_pred_train = model.predict(X_tr)

            test_acc = accuracy_score(y_te, y_pred_test)
            train_acc = accuracy_score(y_tr, y_pred_train)

            print(f"\n=== Best Fold Summary: {name} ===")
            print(f"Train Accuracy: {train_acc:.4f}")
            print(f"Test Accuracy: {test_acc:.4f}")
            print(classification_report(y_te, y_pred_test, target_names=["Control", "Alzheimer's"]))
            break

# ML experiments and tuning

Notes and concerns:
 Are we folding correclty, it looks like we are retraining the best fold, ??? super weird
 Also seems like we need to do more iterations for SVM ... we can get some more out of it 

 Since hte neural nets that havve best aucuracy almost have 1000% in training, should try and do regurlization to try and 'even' out the accuracy between the two

In [ ]:
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.metrics import classification_report, accuracy_score
from sklearn.pipeline import make_pipeline
import numpy as np
import time


import warnings
from sklearn.exceptions import ConvergenceWarning

# Suppress ConvergenceWarnings only
warnings.filterwarnings("ignore", category=ConvergenceWarning)

# Set up test space
kernels = ['linear', 'rbf', 'sigmoid']
Cs = [0.1, 1, 10]
gammas = ['scale', 0.01]  # for rbf/sigmoid
n_estimators = 10
max_iter = 10000

# Replace with your target class names
target_names = ["Control", "Alzheimer's"]

# Loop over kernel/C/gamma
for kernel in kernels:
    for C in Cs:
        if kernel == 'linear':
            label = f"BaggedSVM - linear, C={C}"
            base_model = SVC(kernel=kernel, C=C, probability=False, max_iter=max_iter)
            model = make_pipeline(
                BaggingClassifier(
                    estimator=base_model,
                    n_estimators=n_estimators,
                    max_samples=0.1,
                    n_jobs=3,
                    bootstrap=False,
                    random_state=42
                )
            )
            print(f"\n=== Cross-Validation: {label} ===")
            start = time.time()

            scores = cross_val_score(model, X_train, y_train, cv=15, scoring='accuracy', n_jobs=-1)
            print(f"Mean Accuracy: {scores.mean():.4f}")
            print(f"Standard Deviation: {scores.std():.4f}")
            print(f"All Fold Scores: {np.round(scores, 4)}")

            best_fold_index = np.argmax(scores)
            skf = StratifiedKFold(n_splits=15, shuffle=True, random_state=42)
            for i, (train_index, test_index) in enumerate(skf.split(X_train, y_train)):
                if i == best_fold_index:
                    X_tr, X_te = X_train[train_index], X_train[test_index]
                    y_tr, y_te = y_train[train_index], y_train[test_index]

                    model.fit(X_tr, y_tr)
                    y_pred_test = model.predict(X_te)
                    y_pred_train = model.predict(X_tr)

                    test_acc = accuracy_score(y_te, y_pred_test)
                    train_acc = accuracy_score(y_tr, y_pred_train)

                    print(f"\n=== Best Fold Summary: {label} ===")
                    print(f"Train Accuracy: {train_acc:.4f}")
                    print(f"Test Accuracy: {test_acc:.4f}")
                    print(classification_report(y_te, y_pred_test, target_names=target_names))
                    break

            print(f"⏱️ Duration: {time.time() - start:.1f} sec")

        elif kernel in ['rbf', 'sigmoid']:
            for gamma in gammas:
                label = f"BaggedSVM - {kernel}, C={C}, gamma={gamma}"
                base_model = SVC(kernel=kernel, C=C, gamma=gamma, probability=False, max_iter=max_iter)
                model = make_pipeline(
                    BaggingClassifier(
                        estimator=base_model,
                        n_estimators=n_estimators,
                        max_samples=0.1,
                        n_jobs=3,
                        bootstrap=False,
                        random_state=42
                    )
                )
                print(f"\n=== Cross-Validation: {label} ===")
                start = time.time()

                scores = cross_val_score(model, X_train, y_train, cv=15, scoring='accuracy', n_jobs=-1)
                print(f"Mean Accuracy: {scores.mean():.4f}")
                print(f"Standard Deviation: {scores.std():.4f}")
                print(f"All Fold Scores: {np.round(scores, 4)}")

                best_fold_index = np.argmax(scores)
                skf = StratifiedKFold(n_splits=15, shuffle=True, random_state=42)
                for i, (train_index, test_index) in enumerate(skf.split(X_train, y_train)):
                    if i == best_fold_index:
                        X_tr, X_te = X_train[train_index], X_train[test_index]
                        y_tr, y_te = y_train[train_index], y_train[test_index]

                        model.fit(X_tr, y_tr)
                        y_pred_test = model.predict(X_te)
                        y_pred_train = model.predict(X_tr)

                        test_acc = accuracy_score(y_te, y_pred_test)
                        train_acc = accuracy_score(y_tr, y_pred_train)

                        print(f"\n=== Best Fold Summary: {label} ===")
                        print(f"Train Accuracy: {train_acc:.4f}")
                        print(f"Test Accuracy: {test_acc:.4f}")
                        print(classification_report(y_te, y_pred_test, target_names=target_names))
                        break

                print(f"⏱️ Duration: {time.time() - start:.1f} sec")

In [ ]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import time

# Step 1: Scale data once
scaler = MinMaxScaler(feature_range=(-1, 1))  # You can use (0, 1) if you prefer
X_train_scaled = scaler.fit_transform(X_train)

# Step 2: Define hyperparameter grids
layer_configs = [(100,), (128,), (128, 64), (256, 128, 64)]
activations = ['relu', 'tanh']
alphas = [1e-4, 1e-3, 1e-2]
early_stopping_options = [True, False]

# Step 3: Set up result tracking
results = []
target_names = ["Control", "Alzheimer's"]

# Step 4: Brute-force loop over hyperparameter combinations
for layers in layer_configs:
    for activation in activations:
        for alpha in alphas:
            for early_stopping in early_stopping_options:

                label = f"MLP {layers}, act={activation}, alpha={alpha}, early_stop={early_stopping}"
                model = MLPClassifier(
                    hidden_layer_sizes=layers,
                    activation=activation,
                    alpha=alpha,
                    early_stopping=early_stopping,
                    max_iter=10000,
                    random_state=42,
                )

                print(f"\n=== Cross-Validation: {label} ===")
                start = time.time()

                # Step 5: Cross-validation accuracy scores
                scores = cross_val_score(model, X_train_scaled, y_train, cv=5, scoring='accuracy', n_jobs=3)
                mean_acc, std_acc = scores.mean(), scores.std()
                print(f"Mean Accuracy: {mean_acc:.4f}")
                print(f"Std Deviation: {std_acc:.4f}")
                print(f"All Fold Scores: {np.round(scores, 4)}")

                # Step 6: Find best fold for detailed summary
                skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
                best_fold_index = np.argmax(scores)
                for i, (train_idx, test_idx) in enumerate(skf.split(X_train_scaled, y_train)):
                    if i == best_fold_index:
                        X_tr, X_te = X_train_scaled[train_idx], X_train_scaled[test_idx]
                        y_tr, y_te = y_train[train_idx], y_train[test_idx]

                        model.fit(X_tr, y_tr)
                        y_pred_test = model.predict(X_te)
                        y_pred_train = model.predict(X_tr)

                        train_acc = accuracy_score(y_tr, y_pred_train)
                        test_acc = accuracy_score(y_te, y_pred_test)

                        print(f"\n=== Best Fold Summary: {label} ===")
                        print(f"Train Accuracy: {train_acc:.4f}")
                        print(f"Test Accuracy: {test_acc:.4f}")
                        print(classification_report(y_te, y_pred_test, target_names=target_names))

                        results.append((label, mean_acc, std_acc, train_acc, test_acc))
                        break

                print(f"⏱️ Duration: {time.time() - start:.1f}s")

# Step 7: Final summary sorted by CV accuracy
results.sort(key=lambda x: x[1], reverse=True)
print("\n=== Top Models by Mean CV Accuracy ===")
for label, mean_acc, std_acc, train_acc, test_acc in results:
    print(f"{label:<65} -> CV: {mean_acc:.4f} ± {std_acc:.4f} | Train: {train_acc:.4f} | Test: {test_acc:.4f}")

In [ ]:
%%time
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.metrics import accuracy_score, classification_report
import numpy as np
import time

# Step 1: Scale features if needed (optional for GB, but useful with continuous variables)
X_train_boost = X_train_scaled  # assuming you already have this
X_test_boost = X_test_scaled

# Step 2: Define hyperparameter grid for more complex boosting
n_estimators_list = [100, 200]
learning_rates = [0.05, 0.1]
max_depths = [3, 5, 7]
min_samples_leafs = [1, 3]

# Step 3: Set up result tracking
results = []
target_names = ["Control", "Alzheimer's"]

# Step 4: Manual hyperparameter search
for n_est in n_estimators_list:
    for lr in learning_rates:
        for depth in max_depths:
            for min_leaf in min_samples_leafs:

                label = f"GradBoost n={n_est}, lr={lr}, depth={depth}, min_leaf={min_leaf}"
                model = GradientBoostingClassifier(
                    n_estimators=n_est,
                    learning_rate=lr,
                    max_depth=depth,
                    min_samples_leaf=min_leaf,
                    random_state=42
                )

                print(f"\n=== Cross-Validation: {label} ===")
                start = time.time()

                # Step 5: Cross-validation scores
                scores = cross_val_score(model, X_train_boost, y_train, cv=5, scoring='accuracy', n_jobs=3)
                mean_acc, std_acc = scores.mean(), scores.std()
                print(f"Mean Accuracy: {mean_acc:.4f}")
                print(f"Std Deviation: {std_acc:.4f}")
                print(f"All Fold Scores: {np.round(scores, 4)}")

                # Step 6: Best fold evaluation
                skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
                best_fold_index = np.argmax(scores)
                for i, (train_idx, test_idx) in enumerate(skf.split(X_train_boost, y_train)):
                    if i == best_fold_index:
                        X_tr, X_te = X_train_boost[train_idx], X_train_boost[test_idx]
                        y_tr, y_te = y_train[train_idx], y_train[test_idx]

                        model.fit(X_tr, y_tr)
                        y_pred_test = model.predict(X_te)
                        y_pred_train = model.predict(X_tr)

                        train_acc = accuracy_score(y_tr, y_pred_train)
                        test_acc = accuracy_score(y_te, y_pred_test)

                        print(f"\n=== Best Fold Summary: {label} ===")
                        print(f"Train Accuracy: {train_acc:.4f}")
                        print(f"Test Accuracy: {test_acc:.4f}")
                        print(classification_report(y_te, y_pred_test, target_names=target_names))

                        results.append((label, mean_acc, std_acc, train_acc, test_acc))
                        break

                print(f"⏱️ Duration: {time.time() - start:.1f}s")

# Step 7: Final summary sorted by CV accuracy
results.sort(key=lambda x: x[1], reverse=True)
print("\n=== Top Models by Mean CV Accuracy ===")
for label, mean_acc, std_acc, train_acc, test_acc in results:
    print(f"{label:<75} -> CV: {mean_acc:.4f} ± {std_acc:.4f} | Train: {train_acc:.4f} | Test: {test_acc:.4f}")

In [ ]:
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.metrics import classification_report, accuracy_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier, BaggingClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
import numpy as np

import os

# Define models
models = { # NEED TO GO THORUGH AND MAKE SURE DEFAULTS ARE OK, SHOULD NOT HAVE HAD STANDARD SCALER FOR SVM'S
    # "KNN": KNeighborsClassifier(),
    # "NeuralNet": MLPClassifier(hidden_layer_sizes=(100,), max_iter=10000, random_state=42),
    # "DecisionTree": DecisionTreeClassifier(
    #     max_depth=8,
    #     max_features=None,
    #     min_samples_leaf=10,
    #     min_samples_split=5,
    #     random_state=42
    # ),
    # "GradientBoostedTrees": GradientBoostingClassifier(n_estimators=100, random_state=42),
        # Faster ensemble of SVMs
    # "BaggedSVM": make_pipeline(
    #     StandardScaler(),
    #     BaggingClassifier(
    #         estimator=SVC(kernel='linear', probability=False),
    #         n_estimators=10,
    #         max_samples=0.1,
    #         n_jobs=3,
    #         bootstrap=False,
    #         random_state=42
    #     )
    # ),
    # Classic SVM (can be slow on big data)
    "BaggedSVM": make_pipeline(
        # StandardScaler(),
        BaggingClassifier(
            estimator=SVC(kernel='linear', probability=False),
            n_estimators=10,
            max_samples=0.1,
            n_jobs=3,
            bootstrap=False,
            random_state=42
        )
    ),
}

from sklearn.model_selection import StratifiedKFold

# Run 15-fold CV with parallelization
for name, model in models.items():
    print(f"\n=== Cross-Validation: {name} ===")
    
    # Cross-validation scores
    scores = cross_val_score(model, X_train, y_train, cv=15, scoring='accuracy', n_jobs=-1)
    
    print(f"Mean Accuracy: {scores.mean():.4f}")
    print(f"Standard Deviation: {scores.std():.4f}")
    print(f"All Fold Scores: {np.round(scores, 4)}")
    
    # Get predictions from best-performing fold
    best_fold_index = np.argmax(scores)
    
    # Refit on best 14/15 folds and evaluate on the 1/15
    skf = StratifiedKFold(n_splits=15, shuffle=True, random_state=42)
    for i, (train_index, test_index) in enumerate(skf.split(X_train, y_train)):
        if i == best_fold_index:
            X_tr, X_te = X_train[train_index], X_train[test_index]
            y_tr, y_te = y_train[train_index], y_train[test_index]
            
            model.fit(X_tr, y_tr)
            y_pred_test = model.predict(X_te)
            y_pred_train = model.predict(X_tr)

            test_acc = accuracy_score(y_te, y_pred_test)
            train_acc = accuracy_score(y_tr, y_pred_train)

            print(f"\n=== Best Fold Summary: {name} ===")
            print(f"Train Accuracy: {train_acc:.4f}")
            print(f"Test Accuracy: {test_acc:.4f}")
            print(classification_report(y_te, y_pred_test, target_names=["Control", "Alzheimer's"]))
            break

os.system('say "SVM is done!"')

# ML Testing/tuning # best for nets, tanh 200 hidden layers

In [ ]:
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.metrics import classification_report, accuracy_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
import numpy as np

# Define models
models = {
    # "KNN": KNeighborsClassifier(),
    # "SVM": make_pipeline(StandardScaler(), SVC(probability=True)),
    "NeuralNet": MLPClassifier(hidden_layer_sizes=(200,), activation='tanh', max_iter=10000, random_state=42)
    # "DecisionTree": DecisionTreeClassifier(
    #     max_depth=8,
    #     max_features=None,
    #     min_samples_leaf=10,
    #     min_samples_split=5,
    #     random_state=42
    # ),
    # "GradientBoostedTrees": GradientBoostingClassifier(n_estimators=100, random_state=42)
}

from sklearn.model_selection import StratifiedKFold

# Run 15-fold CV with parallelization
for name, model in models.items():
    print(f"\n=== Cross-Validation: {name} ===")
    
    # Cross-validation scores
    scores = cross_val_score(model, X_train, y_train, cv=15, scoring='accuracy', n_jobs=-1)
    
    print(f"Mean Accuracy: {scores.mean():.4f}")
    print(f"Standard Deviation: {scores.std():.4f}")
    print(f"All Fold Scores: {np.round(scores, 4)}")
    
    # Get predictions from best-performing fold
    best_fold_index = np.argmax(scores)
    
    # Refit on best 14/15 folds and evaluate on the 1/15
    skf = StratifiedKFold(n_splits=15, shuffle=True, random_state=42)
    for i, (train_index, test_index) in enumerate(skf.split(X_train, y_train)):
        if i == best_fold_index:
            X_tr, X_te = X_train[train_index], X_train[test_index]
            y_tr, y_te = y_train[train_index], y_train[test_index]
            
            model.fit(X_tr, y_tr)
            y_pred_test = model.predict(X_te)
            y_pred_train = model.predict(X_tr)

            test_acc = accuracy_score(y_te, y_pred_test)
            train_acc = accuracy_score(y_tr, y_pred_train)

            print(f"\n=== Best Fold Summary: {name} ===")
            print(f"Train Accuracy: {train_acc:.4f}")
            print(f"Test Accuracy: {test_acc:.4f}")
            print(classification_report(y_te, y_pred_test, target_names=["Control", "Alzheimer's"]))
            break

In [ ]:
model = DecisionTreeClassifier(
    max_depth=8,
    max_features=None,
    min_samples_leaf=10,
    min_samples_split=5,
    random_state=42
)

print(f"\n=== Cross-Validation: Regularized DecisionTree ===")

# Cross-validation scores
scores = cross_val_score(model, X_train, y_train, cv=15, scoring='accuracy', n_jobs=-1)

print(f"Mean Accuracy: {scores.mean():.4f}")
print(f"Standard Deviation: {scores.std():.4f}")
print(f"All Fold Scores: {np.round(scores, 4)}")

# Find the best-performing fold
best_fold_index = np.argmax(scores)

# Evaluate best fold manually
skf = StratifiedKFold(n_splits=15, shuffle=True, random_state=42)
for i, (train_index, test_index) in enumerate(skf.split(X_train, y_train)):
    if i == best_fold_index:
        X_tr, X_te = X_train[train_index], X_train[test_index]
        y_tr, y_te = y_train[train_index], y_train[test_index]

        model.fit(X_tr, y_tr)

        y_pred_train = model.predict(X_tr)
        y_pred_test = model.predict(X_te)

        train_acc = accuracy_score(y_tr, y_pred_train)
        test_acc = accuracy_score(y_te, y_pred_test)

        print(f"\n=== Best Fold Summary: Regularized DecisionTree ===")
        print(f"Train Accuracy: {train_acc:.4f}")
        print(f"Test Accuracy: {test_acc:.4f}")
        print(classification_report(y_te, y_pred_test, target_names=["Control", "Alzheimer's"]))
        break

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier

param_grid = {
    'max_depth': [4, 6, 8],
    'min_samples_split': [5, 10, 20],
    'min_samples_leaf': [5, 10, 20],
    'max_features': ['sqrt', 'log2', None]
}

tree = DecisionTreeClassifier(random_state=42)
grid_search = GridSearchCV(tree, param_grid, cv=5, scoring='f1_weighted', n_jobs=-1)
grid_search.fit(X_train, y_train)

print("Best params:", grid_search.best_params_)
print("Best score:", grid_search.best_score_)