In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [3]:
# 1. Load your pickled DataFrames

func = pd.read_pickle("eeg_features_alz_pygrnd6.pkl")
manual = pd.read_pickle("eeg_features_alz_pygrnd5.pkl")

In [6]:
func.head(10)

  Electrode WaveBand SubjectID EpochID     Power
0       Fp1    Delta   sub-020    ep-0 -0.222872
1       Fp1    Theta   sub-020    ep-0  0.234523
2       Fp1    Alpha   sub-020    ep-0  0.652997
3       Fp1     Beta   sub-020    ep-0 -0.389820
4       Fp1    Total   sub-020    ep-0  0.000000
5       Fp2    Delta   sub-020    ep-0 -0.272484
6       Fp2    Theta   sub-020    ep-0  0.329713
7       Fp2    Alpha   sub-020    ep-0  0.454847
8       Fp2     Beta   sub-020    ep-0 -0.190593
9       Fp2    Total   sub-020    ep-0  0.000000

In [7]:
manual.head(10)

  Electrode WaveBand SubjectID EpochID     Power Electrode_WaveBand  label
0       Fp1    Delta   sub-020    ep-0 -0.222872          Fp1_Delta      1
1       Fp1    Theta   sub-020    ep-0  0.234523          Fp1_Theta      1
2       Fp1    Alpha   sub-020    ep-0  0.652997          Fp1_Alpha      1
3       Fp1     Beta   sub-020    ep-0 -0.389820           Fp1_Beta      1
4       Fp1    Total   sub-020    ep-0  0.000000          Fp1_Total      1
5       Fp2    Delta   sub-020    ep-0 -0.272484          Fp2_Delta      1
6       Fp2    Theta   sub-020    ep-0  0.329713          Fp2_Theta      1
7       Fp2    Alpha   sub-020    ep-0  0.454847          Fp2_Alpha      1
8       Fp2     Beta   sub-020    ep-0 -0.190593           Fp2_Beta      1
9       Fp2    Total   sub-020    ep-0  0.000000          Fp2_Total      1

In [9]:
manual = manual.drop(['Electrode_WaveBand', 'label'], axis=1)

In [10]:
func.equals(manual)

True